### ISSUE TITLE
How to convert our Spring project [.jar] to .war file and deploy it on Apache Tomcat 9

### ISSUE THREAD

**Issue by justBeroe** [luchob/softuni-spring-may-2024#11]
Как да деплойнем .jar проекта като .war file и да го стартираме на Apache Tomcat? Is the server port in application.yaml corresponding to Apache Tomcat server port? Трябват ли някакви допълнителни настройки.

Когато си тествах .jarът с java -jar project.jar командата си бачка без проблеми но неможах да го стартирам на Apache Tomcat...

Мерси.

**Comment by luchob** [comment]
Здравей! 

Извинявай за бавния отговор, но избягах този уикенд :-) . Мръсната ми тайна е, че никога не съм деплойвал много спринг приложения на един томкат извън лабораторни условия. Но това трябва да става горе долу така. Ако отвориш любимият ни [spring initializr](https://start.spring.io/) ще видиш, че в packaging има едно тикче - war. Тези проекти добавят едно класче дето изглежда така и е извършва инициализация на сървлет контекста:

```
public class ServletInitializer extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(DemoApplication.class);
	}

}
```

Освен това, се добавя и war плъгин в gradle/maven.  След това, можеш да изпълниш например с maven `mvn clean package` и в таргет директорията на проекта ти ще се появи един war file, например demo-0.0.1.war или нещо подобно. Трябва да го хванеш и да го сложеш в `{TOMCAT_HOME}\webapps` и след това да пуснеш томката. Приложението ще се стартира с контекстен път подобен на името на war file-a, например `http://localhost:8080/demo-0.0.1/hello.

Не знам защо искаш да направиш това нещо, но горе долу така ще стане. Tested (tm) ;-)

Поздрави,
Л.
