### ISSUE TITLE
MobileleUserDetails

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#12]
Здравей, Лъчо,

на последната лекция не разбрах каква е идеята на класа MobileleUserDetails.
Защо го създаваме и в практиката ползва ли се? Прилича ми малко на класа LoggedUsser, който създавахме със @SessionScope.
Има ли как да се избегне?

**Comment by luchob** [comment]
Здравей!

`UserDetailsService`-те се използват в Spring Security когато има аутентикация с потребителско име (username) и парола. 

Идеята е, че Spring Security няма представа как си организирала "съхранението" на юзърите в твоя проект - например, че ги пазиш в таблица с име "users" или защо не "customers", "students" и т.н. Затова има нужда от "преводач", който да преведе твоето представяне на юзърите към нещо от което Spring Security разбира (`UserDetails`). В интерес на истината, ако се спазва определена конвенция в именуването, Spring Security предоставя и готов за ползване UserDetailsService наречен [JdbcDaoImpl](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/jdbc.html). 

Има и готова имплементация ако пазиш user-ите си в паметта - нарича се [InMemoryUserDetailsManager](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/in-memory.html).

Ако мога да обобщя:

- не можеш да ги избегнеш ако използваш `Spring Security` по стандартен начин с username/password аутентикация.
- има готова имплементация, ако спазваш конвенция за именуването. Това не означава че избягваш нещо, а по-скоро че използваш нещо готово.

Поздрави,
Л.
