### ISSUE TITLE
MobileleUserDetails продължение

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#13]
Привет отново,

мисля, че не ми разбра предния въпрос. 
Ясно ми е защо използваме MobileleUSerDetailsService, въпроса ми е относно класа MobileleUserDetails, който екстендва User.
Не може ли да си ползваме UserEntity-то, кое налага създаването на този клас  MobileleUserDetails?

**Comment by luchob** [comment]
Привет, така е - наистина не разбрах, помислих че става въпрос за сървиса. По принцип нищо не го налага и може да се използва `UserEntity`-то. Идеята беше демонстрация на това как работи  `@AuthenticationPrincipal` анотацията:

```
  @XXXMapping("/add")
  public String aMethodInController(@AuthenticationPrincipal MobileleUserDetails seller) {
    //e.g. seller.getFirstName()
  }
```

Това, което връщаш с твоя `UserDetailsService` може да бъде инжектирано като аргумент на контролера. Това дава удобството, да вземаш допълнителна информация за логнатия юзър (например първо и последно име) сравнително лесно, без да правиш заявки към ДБ. Т.е. един по-обогатен `UserDetails` без който може, но с който би могло да е малко по-удобно.

Поздрави,
Л.
