### ISSUE TITLE
Проблем с валидиране на парола

### ISSUE THREAD

**Issue by SavinaDzhenimova** [luchob/softuni-spring-may-2024#14]
https://github.com/SavinaDzhenimova/HomeDeliveryApp

Здравейте! Опитвам да валидирам паролата, която се въвежда при регистрацията на потребител като условията са тя да съдържа поне една главна буква, поне една малка буква, поне една цифра и да е най-малко 8 символа. Опитах с     @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,}$") анотация над полетата за парола, но при използването и въвежданата от мен парола Savina2001 хвърля следната грешка:
 List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must match "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,}$"', propertyPath=password, rootBeanClass=class com.homedelivery.model.entity.User, messageTemplate='{jakarta.validation.constraints.Pattern.message}'}
]] with root cause

jakarta.validation.ConstraintViolationException: Validation failed for classes [com.homedelivery.model.entity.User] during persist time for groups [jakarta.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must match "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,}$"', propertyPath=password, rootBeanClass=class com.homedelivery.model.entity.User, messageTemplate='{jakarta.validation.constraints.Pattern.message}'}
]
При въвеждане на regex-а за паролата в Regex101 паролата Savina2001 отговаря на изискванията. Опитах и да създам собствена анотация @ValidPassword и PasswordConstraintValidator, но приложението гърми със същата грешка. При пускане на debug, когато стигне до ред  51 в UserServiceImpl: user.setPassword(this.passwordEncoder.encode(userRegisterDTO.getPassword())); приложението зависва и не продължава debug режима. Не мога да разбера къде е проблемът.

**Comment by luchob** [comment]
Здрасти!

Когато сложиш в user entity-то (подчертавам ентитито, а не DTO-то което ти носи нещата в контролера) подобна валидация:
```
    @Column(nullable = false)
    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,20}$")
    private String password;
```

тя се включва непосредствено преди записването му в ДБ. Това прави хибернейт. Само че, в password ти записваш не plain-text паролата (напр. Savina2001) а енкоднатата парола:

```
        user.setPassword(this.passwordEncoder.encode(userRegisterDTO.getPassword()));
``` 

Която вече е някакъв огромен стринг и не отговаря на regexp-а в `@Pattern` анотацията ти.

Поздрави,
Л.
