### ISSUE TITLE
Въпрос отностно Docker 

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#16]
*Кратко описание:*

Възможно най-накратко опишете:

Здравейтте , в момента гледам и лекциите от миналото издание на курса и в лекцията за Event Handling от ноември 2023 използваме  MailHog за да тестваме изпращането на confirm-имейлите. Аз успях да го направя , всеки път стартирам mailhog.exe и всичко става , но може ли да обясните какво точно е Docker , тъй като видях , че вие го използвате ? Не мога много да разбера как точно се работи с него и как трябва да го използваме. Също за примера с redis отново се използва Docker , възможно ли е това да бъде направено без него ? Благодаря предварително за отговора и съжалявам , ако не съм задал достатъчно добре въпроса , но нямам никакви познания за Docker.

**Comment by luchob** [comment]
Здравей! 

Имаме една от бонус лекциите за докер, там ще се опитам да го пообясня. Но ако трябва да се опитам да го направя в няколко изречения... 

Представи си, че това е нещо като една много лека виртуална машина. Пускаш я, на нея работи някакъв софтуер, спираш я и той изчезва. Например - трябва ти redis - сваляш си докър имидж на редис и бързо имаш под ръка редис. Трябва ти mysql -> mysql имидж описан на няколко реда, пускаш го и имаш mysql. Спираш и всичко изчезва.

Как работи? Благодарение на фичъри на линукс - cgroups и namespaces които ти дават възможност да пуснеш един процес в изолация, сякаш че работи на отделна OS.

Разбира се, че е възможно да пуснеш всичкия този софтуер и без докър. Няма нещо дето можеш да го пуснеш с докър, но не и без него. Но за разлика от няколкото реда които се изискват за да го подкараш с докър, трябва да инсталираш софтуера и да го конфигурираш на машината където ще го ползваш. След това евентуално да го деинсталираш. И да го ъпгрейдваш. В днешно време, когато работим с множество софтуерни програми (redis, mysql, postgre, mailhog, kafka, prometheus и какво ли още не) и когато деплойваме разни неща в клауд е значително по-лесно това да става с докър.

Как се ползва ли? Първо се инсталира. След това може да имаме докър компоуз файл като [моя](https://github.com/luchob/softuni-spring-may-2024/blob/main/local-docker/docker-compose.yaml).

Тук в момента има само mysql, но има и коментирани redis, prometheus, grafana, kafka и zookeper. Всичкия този софтуер се пуска с команда като
```
docker-compose -d docker-compose.yaml up
```

Поздрави,
Л.

**Comment by baldzhiyski** [comment]
Благодаря много за обяснението
