### ISSUE TITLE
LoggedUser

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#17]
Привет Лъчо,

след въвеждането на Spring Security функцията на LoggedUser отпада, но как да го заместим, от къде да вземем логнатия в момента потребител.
Например ако в Mobilele при добавянето на оферта искам да задам и кой потребител я е добавил как да го взема?

Поздрави,
Петя

**Comment by BogoevaPetya** [comment]
В презентацията от последната лекция пише, че това става с Principal, но как да го подам
напр. offer.add(...) и очаква да подам User. Как този Principal да стане User...

**Comment by luchob** [comment]
Здравей!

Може да опиташ с принципал, но и с `@AuthenticationPrincipal`. Например, в контролера:
```
 @GetMapping("/")
  public String home(@AuthenticationPrincipal UserDetails userDetails)
``` 

Каквото връща твоя `UserDetailService` това можеш да инжектираш в контролера както обсъдихме [тук](https://github.com/luchob/softuni-spring-may-2024/issues/13). Оттам нататък, достъпът до `User` ентитито (допускам то ти е нужно) е сравнително лесен и може да се осъществи през юзър репозиторито, например:

``` 
userRepository.findByEmail(mobileleUserDetails.getUsername()) // <- returns the entity
```

Поздрави,
Л.

**Comment by BogoevaPetya** [comment]
Много благодаря, стана ми ясно :)
