### ISSUE TITLE
Pathfinder

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#18]
Привет, Лъчо,

на упражнението вчера с Pathfinder-a правихме валидации на логин формата, ако не се предоставят правилни username и парола да пренасочим към login-error страница и да изпище съобщение във формата, но при мен не се получават нещата.
Би ли погледнал и да ме насочиш къде греша?
https://github.com/BogoevaPetya/Pathfinder

Поздрави,
Петя

**Comment by luchob** [comment]
Здрасти, Петя!

Виждам няколко дребни проблемчета... 

Прбелем но 1: Ендпойнтът login-error не е разрешен за всички юзъри. И когато редиректнеш нелогнатия юзър към него тъй като е забранен те пренасочва към логин страницата вместо да попаднеш там. Това е лесно поправимо:

``` 
.requestMatchers("/", "/users/login", "/users/register", "/users/login-error").permitAll()                 
``` 

Проблем но 2. е че между `failureUrl` и `failureForwardUrl` има една тънка разлика, която няма да ти позволи да изпишеш юзърнейма при неуспех за да не е необходимо юзъра да го пише наново (стига да искаш така да работи). Погледни описанието на разликата [тук](https://github.com/luchob/softuni-spring-may-2024/issues/6) тъй като е важно и итгересно.

Ако искаш, може да продължиш с `formLogin.failureForwardUrl("/users/login-error");` и да смениш на пост мапинг, например така:

``` 
 @PostMapping("/users/login-error")
    public String viewLoginError(@ModelAttribute("username") String username, Model model){

        UserLoginDTO userLoginDTO = new UserLoginDTO();
        userLoginDTO.setUsername(username);

        model.addAttribute("showErrorMessage", true);
        model.addAttribute("userLoginDTO", userLoginDTO);
        return "login";
    }
``` 

В интерес на истината  може да го опростиш още повече - `UserLoginDTO`дори не ти е необходимо, може да имаш само един параметър - username, който е String.

Поздрави,
Л.

**Comment by BogoevaPetya** [comment]
Ехааа, супер обяснение на разликата, което си направил със схема!
Определено на лекциите не остава време да се отдели внимание на всичко и като почнем да пишем излизат доста проблеми. Благодаря, че отделяш време да обясняваш така подробно!
