### ISSUE TITLE
Използване на Java Script + Rest API ( Желание ) 

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#19]
Здравейте , ако в някоя от лекциите остане време бихте ли показали още някой пример с java script и фечване с js , както направихме със смяната на стойностите спрямо избраната валута ? Аз разбрах начина , по който се прави , но би било полезно да видя още някой пример. Благодаря предварително !

**Comment by luchob** [comment]
Здравей, тъй като непосредствено не виждам къде ще го направим в мобиле - предадох желанието на колегите с упражненията. Според тях в workshop-a има едно място, където ще се наложи с JS да дърпате данни от бекенда през REST. Това ще стане при четенето на картите. Надявам се, да стигне малкото време и да успеете да го направите.

Поздрави,
Л.
