### ISSUE TITLE
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by NikolayGeorgievv** [luchob/softuni-spring-may-2024#2]
Здрасти Лъчо,
Извинявай, че не можах да ти отговоря в лекцията, просто ми се наложи да стана по спешност.
https://github.com/NikolayGeorgievv/BudgedTrackerProject Това е линка към проекта. Няколко изречения за повече контекст:
Използвам кажи-речи един и същ подход да визуализирам данни от базата в приложението: с таблици. Имам таблица с акаунти, която работи, таблица със сметки, която също работи. 3тата таблица, където е проблема е с "Goals". Там ми визуализира може би само 1вото ентити или нищо. Даже понякога не се рендерират други части от страницата, като сайдбар-а. Както каза на лекцията, едва ли е от размера на хедъра, понеже данните, които реално се опитвам да предам на другите ендпоинти са по-големи(например разходите) и съм нямал проблеми. 
Благодаря за съдействието, 
Поздрави!

**Comment by luchob** [comment]
Добро утро!

Според мен истинската ти драма идва от решението да добавиш това в `application.properties` :-)

```
logging.level.org = false
```

С това си заглушил всички логове на thymeleaf, т.е. като има проблеми при парсването на темплейта ти няма да ги видиш и ще имаш приключения като това, в което си в момента. Ако го махнеш, грешката на страничката ти веднага ще стане очевидна в логовете ти:

```
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "a.getId()" (template: "allGoalsPage" - line 86, col 106)
```

Където, макар и в коментар действително имаш:

```
th:onclick="newValue(/*[[${a.getId()}]]*/)"
```

Очевидно [text inline-a](https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#inlining) работи дори и в коментар. 

Нямаше начин как да ти отговоря на този проблем на лекцията :-)

Поздрави,
Л.

**Comment by NikolayGeorgievv** [comment]
Добро утро!
Благодаря много за съдействието и бързия отзив! Абсолютно си прав, кода в
коментар очевидно е копи-пейст, който още не е преработен. Дори и след
милион години не бих се сетил, че text-inline-a работи в коментар?! Нямаш
идея колко много мъки ми спести, вчера цял ден разглеждам за този ерор,
опитвах се да го разреша с responseEntity, headers и т.н., изчетох 1 тон
документация, а то какво било. Малко ме е срам, че не се сетих да променя
логинг левела и да дебъгна като нормален човек, просто знаеш как е като
влезеш в зоната.
Благодаря пак, може би тук е момента да кажа, че съм гледал твои предишни
издания и много ти се кефя, доста ми допада начина ти на преподаване и се
радвам, че си мой лектор и имам възможността да се уча от теб. 11/10
Поздрави,
Николай.
