### ISSUE TITLE
Достъп до НЕ разрешена страница

### ISSUE THREAD

**Issue by MileneAngelova** [luchob/softuni-spring-may-2024#20]
Привет!

Имам следните проблеми:
1.  Имам достъп до offers/add  като НЕлогнат потребител. Не съм разрешавала страницата в SecurityConfiguration файла.
2. След като добавих Spring Security нямам достъп до детайлите на офертата. Излиза следната грешка: Offer.getSeller()" is null.
    Може ли да удариш едно рамо как да го фиксна, че сама не успях  :)
Ето линк към репозиторито:   https://github.com/MileneAngelova/MobiLeLe

THANK YOU!

**Comment by luchob** [comment]
Здрасти! 

Много ясно че ще ударя. Относно 1 отговорът изглежда що годе прост. Имаш:
```
.requestMatchers(..., "/offers/{id}").permitAll()
``` 

Което успява да мачне и `offers/add` :-) Защото си мисли, че add е някакво id. Просто трябва да си промениш (или променим :( ) имената и ще тръгне. 

За втория въпрос може би ми трябва повече контекст. Никъде не видждам да се използва setSeller(..) така че очаквам нещо като ... Offer.getSeller() is null. Къде слагаш продавача при създаването на офертата?

Поздрави и може би до 18:30,
Л.

**Comment by luchob** [comment]
Да, всъщност проблем 1) аз съм го объркал :-)

**Comment by MileneAngelova** [comment]
offer.getSeller го ползвам в String формата на OfferServis-а:

private OfferDetailsDTO toOfferDetails(Offer offer) {
        return new OfferDetailsDTO(offer.getId(),
            ......
            .......
                String.format(offer.getSeller().getFirstName() + "  " + offer.getSeller().getLastName()),
            .....
       }

Преди да добавя Spring Security работеше много добре с Current user.
Ползвам го да покажа кой потребител е качил офертата.

**Comment by luchob** [comment]
Добро утро! :-) 

Направихме един find+replace за order->offers, но това е положението - цял ден някой повтаря "orders" около мен.

Пак относно първия проблем, може да го решим адски лесно с малко пренареждане, ето така:

```
.requestMatchers("/offers/add").authenticated()
.requestMatchers(...."/offers/{id}").permitAll()
```

Доколкото виждам в документацията ги държи като лист, така че първото би трябвало да има приоритет пред второто. Т.е. ако има /offers/add ще се задейства matcher-a който е за authenticated.

Относно втория проблем, очевидното което трябва да се направи е да се поправи коментирания код, за да се зададе текущия юзър:

```
    public void addOffer(AddOfferDTO addOfferDTO) {
         ...
//        UserEntity seller = userRepository.findByEmail(currentUser.getEmail()).orElse(null);
//        System.out.println(currentUser.getEmail() + " " + currentUser.getName());
   
//        newOffer.setSeller(seller);
          ...
    }
```

Можем да подадем един аргумент в метода, напр:
```
    public void addOffer(AddOfferDTO addOfferDTO, String sellerEmail) {
         ...
        UserEntity seller = userRepository.findByEmail(currentUser.getEmail()).orElse(null);

        newOffer.setSeller(seller);
          ...
    }
```

За да го вземем от контролера, може да се използва анотацията `@AuthenticationPrincipal`. Пример:
```
@PostMapping("/add")
    public String addOffer(@Valid AddOfferDTO addOfferModel,
        BindingResult bindingResult,
        RedirectAttributes redirectAttributes,
        @AuthenticationPrincipal UserDetails currentUser) {


        ....
        this.offerService.addOffer(addOfferModel, currentUser.getUsername());
        return "redirect:/offers/all";
    }
```

Надявам се, това да помогне!

Поздрави, 
Л.

П.П. Остава да видя защо baseUrl-a не работеше :-)

**Comment by luchob** [comment]
baseUrl-a не работеше, защото в конфигурацията пишеше order, вместо offer 🤣
А сега пък ще трябва да дебъгна един ордър 🤭
