### ISSUE TITLE
Failed to load ApplicationContext Integrational Test

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#21]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*

https://github.com/baldzhiyski/Crossfit-Web-App/commit/5b07e73b1a742f70b1df8260dd080798224a9f3b

Също теста за rest api файлва със същата грешка : https://github.com/baldzhiyski/Crossfit-Web-App/commit/36ac00b9b8edbca8ca9793cd8658a9bf9e15d633

*Кратко описание:*

Здравейте , изгледах лекцията от септември 2023 за тестовете и направих същия integration test 1:1 с малки промени в yaml файла за exchange rates , но не може да loadne АpplicationContexta . Ако може да ми кажете къде греша ? Изписва също , че като иска да направи GET заявна към API няма такова url . Но нали трябва да пишем тестови url и а не истинския , защо тогава изписва това съобщение ( по точно : I/O error on GET request for "https://dummy/second": null ) . Благодаря за помощта предварително !

**Comment by luchob** [comment]
Здравей!

Независимо дали е тест или не, апликейшън контекста се вдига по абсолютно същите правила и в края на крайщата се извършва въпросната заявка, който гръмва по очевидни причини. Т.е. трябва да имаш начин да предодвратиш това или пък да направиш някакъв mock service който да сервира рейтове и страни. Хрумват ми няколко решения, ще ги изброя и ще се концентрирам върху едно:

- с профили
- с mock service, например използвайки wiremock
- с някакво пропърти

Тъй като последното ми звучи най-лесно, ще ти покажа какво имам предвид в контекста на нашия проект. Ето как в mobilele изглежда класа дето дърпа валутите по REST:

``` 
@Component
public class ExchangeRateInitializer implements CommandLineRunner {

  private final ExRateService exRateService;

  public ExchangeRateInitializer(ExRateService exRateService) {
    this.exRateService = exRateService;
  }

  @Override
  public void run(String... args) throws Exception {
    if (!exRateService.hasInitializedExRates()) {
      exRateService.updateRates(
          exRateService.fetchExRates()
      );
    }
  }
}
```

Нищо особено. Но може да му сложа и една допълнителна анотация, с която не съм ви запознавал:
```
@ConditionalOnProperty(name = "forex.api.init-exchange-rates", havingValue = "true")
@Component
public class ExchangeRateInitializer implements CommandLineRunner
``` 

Анотацията се чете така: "Направи бийн от този компонент, само ако съществува това пропърти `forex.api.init-exchange-rates` и неговата стойност е `true`. В противен случай подмини класа.".

Тогава в истинското `application.yaml` поставям:

```
forex:
  api:
    key: ${FOREX_API_KEY:}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"
    init-exchange-rates: true
``` 

А в тестовото изпускам `init-exchange-rates` (или го слагам false) и бийна няма да влезе в тестовия контекст. Така ми изглежда най-просто. Иначе в лекцията за интегрейшън тестовете ми се иска да ви запозная и с wiremock. Представи си, че това е един http сървър който се пуска заедно с теста, който може да инструктираш да ти връща тестови json snippet-и при определени заявки. Все едно mock openexchangerates. Доста е полезно и си поиграх да го подкарам точно в контекста на mobilele. 

Надявам се да помогне, ако не - пиши.

Поздрави,
Л.

**Comment by baldzhiyski** [comment]
Здравейте , всичко проработи сега . Благодаря ви и ще чакам лекцията за тестовете от този курс , за да разбера повече за този wiremock . Също исках да попитам според вас да пишем ли повече Junit тестове за сървисите или повече IT тестове ? Тъй като аз разбирам разликата между двата вида , но не знам дали за всеки сървис трябва да пиша и Junit  и IT test  или да си избера един от двата вида

**Comment by luchob** [comment]
Здравей, както прецениш! 

Въпросът е да имаш смислен line coverage :-) По-принцип теорията твърди че трябва да се придържаме към тестовата пирамида - отдолу има много unit тестове, отгоре - по-малко интегрейшън. Където има някакви сметки като например в нашия валутен сървис е особено добре да е покрито с unit тестове.

Поздрави,
Л.
