### ISSUE TITLE
Въпрос относно mobilele-то

### ISSUE THREAD

**Issue by ShenolShengov** [luchob/softuni-spring-may-2024#22]
Зравей, Лъчо!
Аз имам един въпрос относно mobilele-то. На офертите не трябва ли да имам поле User addedBy или нещо от сорта, за да знаем кой е създал офертата. Нали искам в allOffers страницата да даваме въжможност на този, който е създал офертата да може да я изтрие. Как ще стане това?

**Comment by luchob** [comment]
Здравей! 

Да, трябва да има за да асоциираме оферта с user. Вчера си говорих по този въпрос с колежката ни в [issue 20](https://github.com/luchob/softuni-spring-may-2024/issues/20). Единият и от двата проблема е точно с юзъра, ако искаш хвърли едно око там, а защо не и в проекта и. Малко "столкване" никога не вреди :-)  (програмирането си е групова дейност в реалния живот ;-) )

Поздрави,
Л.
