### ISSUE TITLE
Проблем с multiply selector и показване на дата

### ISSUE THREAD

**Issue by BlagoyVelinov** [luchob/softuni-spring-may-2024#23]
*Връзка към проекта:*

https://github.com/4ukNoris/Spring-Project/tree/master

*Кратко описание:*

Здравей, Лъчо
 Имам следния проблем: Не знам как да взема избрана дата от program страницата и да се покаже на същата страница на полето което и е отредено да се показва.
 Другия проблем е: бях те питал в sli.do за multiply селектор дали може да се направи по елегантно от това което съм направил аз в темплийта add-movie!
 
Възможно най-накратко опишете:

1. Какво очаквате да се случи
2.  Очаквам датата да се показва в полето
3. Какво всъщност се случва
4.  Нищо не се случва
5. (Желателно) Какво опитахте
6.  Не съм опитвал нищо.

*Стъпки за репродуциране:*

 За сега това което ми идва на ум е да взимам дата с post  и да я връщам с get но това е най - крайния вариант който според мен ще е много грозен и не ми се иска да го правя.

**Comment by luchob** [comment]
Здравей, относно първия ти проблем - не съм сигурен че те разбирам добре, но ще опитам да възпроизведа разбраното :-) 

Вариант 1: Ако целта ти е да показваш дадена дата избрана в date input-a на друго място може да използваш javascript:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Date Input Example</title>
</head>
<body>
    <label for="dateInput">Select a date: </label>
    <input type="date" id="dateInput">

    <div id="displayDate"></div>

    <script src="script.js"></script>
</body>
</html>
```

```
document.addEventListener('DOMContentLoaded', function() {
    const dateInput = document.getElementById('dateInput');
    const displayDate = document.getElementById('displayDate');

    dateInput.addEventListener('change', function() {
        const selectedDate = dateInput.value;
        displayDate.textContent = `Selected date: ${selectedDate}`;
    });
});
```

Ето го в действие с jsfiddle -> https://jsfiddle.net/b3mndhkp/


Вариант 2: Ако искаш да е сърч на сървъра, който да ти връща прожекциите за даден ден правиш GET заявка при смяна на датата (с javascript), избираш прожекциите и попълваш датата в thymeleaf (слагаш я в модела заедно с прожекциите).

**Comment by luchob** [comment]
Относно multiple select-a точно така си го представям и точно за това служи select с  multiple опция. Може и с чекбоксчета да го направиш ако ти се занимава, но мисля че е излишно и така е достатъчно.

Поздрави,
Л.

**Comment by BlagoyVelinov** [comment]
Много благодаря, Лъчо. Ще пробвам скрипта за датата и щом това е достатъчно за проекта няма да го пипам, че още доста работа ме чака😊
