### ISSUE TITLE
Използване на RestController

### ISSUE THREAD

**Issue by SavinaDzhenimova** [luchob/softuni-spring-may-2024#24]
Здравей! Нямам конкретен въпрос към част от моя проект. Въпросът ми е свързан с едно от изискванията за финалния проект. В една от подточките пише: "Include logic in a separate service with a Rest Controller, consumed by another service via a Rest Client."
След като изгледах лекцията от четвъртък вечер, където показваш как да създадем RestController и след това да си дръпнем информацията с помощта на RestClient стигам до извода, че трябва да изкарам поне едно entity от проекта си, да го направя на отделно приложение с Repostiory, Service и RestController и след това във финалния си проект просто чрез RestClient в един от сървисите (този за конкретното entity, което съм изкарала в отделен проект) да си взимам информацията и чрез обикновен Controller да я подавам към html страницата, в която я използвам. Правилно ли съм разбрала каква е идеята понеже за момента този RestController е единствената част от проекта, която ме затруднява и не мога да схвана какво точно трябва да се направи.

**Comment by luchob** [comment]
Здравей! 

Абсолютно правилно си разбрала. Мога дори да обясня откъде идва това изискване. В предишните издания на курса имаше изискване да имаме RestController и той да се консумира с JavaScript от някакъв template. Да, обаче това изисква поне малко над основни познания в JS (които не всички студенти имаха) и курса по спринг се превърна в курс по Javascript :-) За да спестим тези неудобства решихме да го преместим изцяло в Spring и да може да свикнете да правите двете важни неща в контекста на спринг - да консумирате REST API и да продуцирате такова с RestController-и. Неща, с които ще се сблъскате в почти всеки един реален проект. Така че, изкарай най-простото ентити извън проекта и комуникирай с него през REST. Сигурен съм, че ще се справиш - ако не - ще помагам.

Избрахме RestClient защото е най-актуалния за spring mvc. RestTemplate вече е поумрял, а WebClient-а (с който съм свикнал :-) ) е част от webflux е може да е доста объркващ на пръв поглед.

Поздрави,
Л.

BTW RestClient-a не ми тръгна на лекцията, защото конфигурацията беше объркана. order вместо offer :D

**Comment by baldzhiyski** [comment]
Здравейте , отностно същия въпрос трябва ли да създадем  нов проект ,  в който да направим Rest Controllera , или може в същия проект да си направим Rest Controllera + Rest Clienta ? И ако направим нов проект и пускаме get заявка , няма ли да е необходимо да бъде стартиран и той също и така да имаме проблем , тъй като и двете неща са на един и същи порт ?

**Comment by luchob** [comment]
Здравей! 

Според мен би било по-образователно проектите да са 2, отделни. Това го пише и в изискванията:

_Include logic in a separate service with a Rest Controller, consumed by another service via a Rest Client._

Относно порта, това не е проблем тъй като порта на който се стартира спринг приложението се конфигурира лесно. Просто добави следната конфигурация в `application.yaml` или `application.properties` ако искаш порта да е 8081 например:

```
server:
  port: 8081
```

Поздрави,
Л.
