### ISSUE TITLE
Как да приложа Spring Security в Rest Client-а, когато базата данни с users е в Rest Server-a?

### ISSUE THREAD

**Issue by mr-pachev** [luchob/softuni-spring-may-2024#26]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*
Rest Client -> https://github.com/mr-pachev/human-resource-managements.git
Rest Server -> https://github.com/mr-pachev/hrm-users.git

*Кратко описание:*

Възможно най-накратко опишете:

1. Какво очаквате да се случи - проверка от Spring Security (проверява в базата дали съществува такъв потребител).
2. Какво всъщност се случва - нищо :-D
3. (Желателно) Какво опитахте - когато данните за users са записани в Rest Clienta всичко работи, както трябва, но не знам как да използвам Spring Security, когато данните са в Rest Server-a.

*Стъпки за репродуциране:*

Нямам идея. 

Дано да не досаждам прекалено. Боря се да изпълня изискването за ползването на Rest във финалният проект и последно реших users да се пазят в Rest Server-a.

Благодаря предварително.

**Comment by luchob** [comment]
Оки, считам issue-то за затворено.

Поздрави,
Л.

**Comment by mr-pachev** [comment]
Да, вчера на лекцията получих нужният ми отговор а именно - не трябва да си усложнявам излишно живота :-D. Смених концепцията - user остава в Rest Client-a, за да работи Spring Security.
