### ISSUE TITLE
Проблем при нанасяне на данни в DB.

### ISSUE THREAD

**Issue by YoanMarinov17** [luchob/softuni-spring-may-2024#28]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*
https://github.com/YoanMarinov17/Rent-Vehicle-Final-Project

*Кратко описание:*
Здравей Лъчо ! Темата на проекта  е приложение за отдаване под наем на превозни средства като  даден user може да отдава под наем кола/ван/камион, а в същото време друг юзър може да ги взима под наем. 
Понеже имам основен клас Vehicle и подкласове Car, Van,Truck, които го наследяват, искам да добавям Vehicle заедно с подкласовете в базата данни, но когато тръгна да добавям дадено превозно средство и нищо не се случва. (Целта е  да вкарам превозното средство и неговия подтип (например кола) на user-a, който иска да отдаде превозно средство под наем в DB.) Моля за помощ !

Възможно най-накратко опишете:

1. Какво очаквате да се случи
2. Какво всъщност се случва
3. (Желателно) Какво опитахте

*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които бързо може да се репродуцира проблемът.

**Comment by luchob** [comment]
Здравей, може ли малко подробности какво ознаава че нищо не се случва? Ето, например - свалям проекта и добавям следния код:

```
@Component
public class Test implements CommandLineRunner {

  @Autowired
  private VehicleService vehicleService;

  @Override
  public void run(String... args) throws Exception {
    vehicleService.createVan(
        new VehicleDto()
            .setEngine(EngineEnum.DIESEL)
            .setModel("model")
            .setYear(2021)
            .setType(TypeEnum.CAR),
        3
    );
  }
}
```

Гледам логовете от хибернейт:

```
insert 
    into
        vehicles
        (engine, model, type, year) 
    values
        (?, ?, ?, ?)

insert 
    into
        vans
        (number_seats, id) 
    values
        (?, ?)
```

Виждам, създадени редове във vehicles и vans (e, този във vans е леко бъгав, няма number_seats но причината е в сървиса). Т.е. всичко горе е според очакванията, тествам на последната версия на проекта.

Поздрави,
Л.

**Comment by YoanMarinov17** [comment]
Здравей Лъчо !
Промених още малко нещата в сървиза (ModelMapper), за да може да се сетват
нормално нещата при Van и Truck.
Проблемът ми е, когато влезна в Localhost и влезна в Service -> Give
vehicle for rent -> нанеса необходимите данни за Car/Van/Truck и директно
ме препраща на страницата за Login. А в SecurityChain-а съм позволил да
имам достъп до тази страница без да има нужда от логване.
След като си въведа данните и опитам да добавя отново Vehicle ми излиза
грешка 400/404.
Откъде може да има проблема ?
Ъпдейт на проекта е качен в GitHub.
Поздрави, Йоан

**Comment by luchob** [comment]
Здравей!

За съжаление в  [templates](https://github.com/YoanMarinov17/Rent-Vehicle-Final-Project/tree/main/src/main/resources/templates) не си push-нал `add-vehicle.html`, която е съмнителна :-) Може ли да я довавиш?

Поздрави,
Л.

**Comment by luchob** [comment]
Здравей, вече виждам, че е добавен.

Препраща те на логин страницата защото:

1. Имаш exception при записването на превозното средство
2. Spring те препраща към `/error` page-a, но той е забранен за нелогнати юзъри
3. Тъй като е забранен, те препраща към логин страницата

Ако разрешиш `/error` ще виждаш whitelabel error page-a.

А самият ексепшън е този: 
```
org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.softuni.Rent_Vehicle_Company.model.entity.Car.user -> org.softuni.Rent_Vehicle_Company.model.entity.User
```

Какво означава този exception, можеш да прочетеш последния ми коментар в [issue #5](https://github.com/luchob/softuni-spring-may-2024/issues/5). 

Поздрави,
Л.
