### ISSUE TITLE
The bean 'localeResolver', defined in class path resource

### ISSUE THREAD

**Issue by NikolayGeorgievv** [luchob/softuni-spring-may-2024#29]
https://github.com/NikolayGeorgievv/BudgedTrackerProject

Здрасти Лъчо. 
Бях се опитвал да правя интернационализация преди време, като следвах стъпките от Baeldung: https://www.baeldung.com/spring-boot-internationalization

Първо го тествах, като си направих един нов проект и всичко си тръгна нормално, както е в гида. После, реших да го направя същото нещо и в моят проект, но получих следният ерор: 

"The bean 'localeResolver', defined in class path resource [org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/burdettracker/budgedtrackerproject/config/I18NConfig.class] and overriding is disabled."

 Пробвах различни неща от нета, не сработи и реших да го оставя и да видя как ще го направиш ти. 
Сега като следвах твоите стъпки, получавам същият проблем. Ако преименувам бийна получавам друг ерор:

"Request processing failed: java.lang.UnsupportedOperationException: Cannot change HTTP Accept-Language header - use a different locale resolution strategy"

Четох някъде, че може би се получава от различни версии на депенданситата, но не съм сигурен как да проверя или дебъгна такова нещо. Позволяването на пренаписването на бийнове, както е предложено в ерор съобщението до колкото разбрах е лоша практика и предпочитам да не го правя.

За да придобиеш по-добра представа, разкоментирай "@Configuration" анотацията в I18NConfig и LocaleChangeInterceptor-a в WebConfig класа и стартирай приложението.
Моля те, дай акъл. Благодаря, 
Поздрави,
Николай.

**Comment by luchob** [comment]
Привет, Ники!

Мисля, че целият ти проблем идва от използването на `@EnableWebMvc` анотацията. По принцип тя се ползва, за да сложиш MVC съпорт в някакво спринг приложение. Но когато имаш spring boot това става с auto-configurations и когато сложиш тази анотация тя override-ва тези конфигурации. С други думи става "боза".

Затова смятам, че можеш да я изтриеш и нещата трябва да проработят.

Поздрави,
Л.

**Comment by NikolayGeorgievv** [comment]
Здрасти Лъчо,

Мерси за бързият отговор. Абсолютно си прав, както винаги. Това съм го конфигурирал още в началото, понеже имах друга идея за проекта, някакви неща не ми се случваха и от ровене в нета намерих това решение за тогавашният проблем, та съм го забравил да го махна.

Как да е, мерси много, топ си!

Поздрави,
Николай.
