### ISSUE TITLE
Валидация на pop-up form.

### ISSUE THREAD

**Issue by NikolayGeorgievv** [luchob/softuni-spring-may-2024#3]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*

[Линк към проекта](https://github.com/NikolayGeorgievv/BudgedTrackerProject)

*Кратко описание:* Здрасти Лъчо, пак съм аз. Понеже вчера беше лекцията за валидация и Thymeleaf, та един бърз въпрос по темата: Има ли начин да валидирам pop-up форма и как да върна темплийта?

Възможно най-накратко опишете:
На кратко: Юзъра ползва pop-up форми за различни цели(напр. създаване на expense).По default формата е скрита(display="none") и чрез бутон се визуализира. Валидацията си работи и като трябва да върна същата страница, я връщам без формата да е display-ната. (стайлинга се ресетва).  В момента съм го подкарал, като съм направил копие на страницата, и по default формата в копие-страницата е display="block", и така, като я върна си показва формата с ерор съобщенията. Мога ли някак да го подкарам това чудо без екстра файла или някакъв бесен JS и Spring микс(нямам идея дали е възможно, търсих самостоятелно, но не ми излезе нищо конкретно). Притеснява ме изпитващите да не го отчетат за грешка, а аз просто искам да направя по-хубав UI.(поне за мен, иначе е доста по-лесно да се направи с отделни странички)

*Стъпки за репродуциране:* В момента по този начин работи само добавянето на "Expense"(account и goal съм ги валидирал само на фронт-енд-а). Можеш лесно да видиш за какво говоря и да се ориентираш, като просто се опиташ да добавиш expense и оставиш едно от полетата празно.

Благодаря за отделеното време, 
Поздрави,
Николай.

**Comment by luchob** [comment]
Здравей, извинявай за бавния отговор!

Не е съвсем лесно да се ориентирам :-) Не може ли да направиш нещо от сорта. Да имаш два класа:

```
.form-displayed {
    display: block;
}

.form-hidden {
    display: none;
}
``` 

И в thymeleaf-a просто да добавиш нещо от сорта на:

```
<div class="form-popup1" id="myExpenseForm" th:classappend="${#fields.hasErrors('*')} ? form-displayed : form-hidden">
...
</div>
```

Поздрави,
Л.

**Comment by NikolayGeorgievv** [comment]
Лъчо, голям си. Когато човек дори не знае какво не знае, става пълна
лудница. Мерси много.
Поздрави,
Николай.
