### ISSUE TITLE
i18n не работи?

### ISSUE THREAD

**Issue by mr-pachev** [luchob/softuni-spring-may-2024#30]
*Връзка към проекта:*
https://github.com/mr-pachev/human-resource-managements.git

*Кратко описание:*

Възможно най-накратко опишете:
1. Създаден и конфигуриран I18NConfig
2. Създаден и конфигуриран WebConfig
3. Създадена папка i18n съдържаща двата файла: messages.propetries и messages_bg.propetries в resources 
4. В template-a по шаблон от вчерашната лекция добавени thymeleaf компонентите

*Стъпки за репродуциране:*
При стартиране на приложението се показва само българската версия на надписите. При проверка в добавката на браузъра - EdithThisCookies - бисквитките се сменят bg_BG и en_US.

Следвах стъпка по стъпка показаното на вчерашната лекцията, но при мен нещо не разпознава може би lang.
Нямам идея защо не сработва при мен.

Много ще съм благодарен за насоки относно решение на проблема. 
Благодаря предварително.

**Comment by luchob** [comment]
Привет! 

Опасявам се, че при мен работи, което пък ми напомня за един много стар и тънък проблем. Допускам, че причината е, че работиш на машина с българска локализация :-) Имахме такъв проблем тук - https://github.com/luchob/softuni-feb2023/issues/88  и стана голяма работа.

Ако ти е БГ локала, то си мисли, че по-подразбиране messages_bg е default и после търси messages_en като смениш на английски. Но тъй като такова няма, прави fallback към messages_bg... Може ли да прекръстиш messages.properties на messages_en.properties за да потвърдим подозрението? 

99% съм сигурен, че е това. Ще съм благодарен ако потвърдиш.

Поздрави,
Л.

**Comment by mr-pachev** [comment]
Наистина съм с БГ локал. Смених името на файла. Промени се това, че по подразбиране показва само английската версия, но не сменя езиците? Изтърках и бисквитките и данните от сърфипанията в chrome и няма промяна. Ще сменя езика на Windows-a на EN, ако има отношение?

**Comment by mr-pachev** [comment]
Смених езиковият пакет на Windows-a на EN и промених името на файла от messages_en към messages_bg.properties -> сработи, НО това не ми се струва много практично, защото не се знае потребителя, който ще ползва това приложение дали няма да е с български настройки на компютъра си.

**Comment by luchob** [comment]
Абсолютно си прав, с малкото допълнение че става въпрос не за потребителя а за сървъра. Затова може да направим така.

Може да сложим 2 файла:
```
messages_en.properties
messages_bg.properties
```

Остава неприятния въпрос - ако не е сетнат локал или се сетне по някаква причина 3-ти локал - кой от двата файла да се вземе, т.е. кой да е default? Може да постигнем това с допълнителна настройчица, с използването на `setDefaultLocale`. А именно:

```
  @Bean
  public MessageSource messageSource() {
    ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
    messageSource.setBasename("classpath:i18n/messages");
    messageSource.setDefaultEncoding("UTF-8");
    messageSource.setDefaultLocale(Locale.ENGLISH);//<---- тук
    return messageSource;
  }
```

**Comment by mr-pachev** [comment]
Лъчо ти беше прав.

**Comment by mr-pachev** [comment]
Става само със смяна на името на файла от messages_bg на message_en (НЕ us) и работи независимо какъв езиков пакет използва Windows-a.

Точно в десетката. 
Благодаря отново.
