### ISSUE TITLE
При стартиране на проекта Mobilele и отваряне директно на оферта, сървъра забива.

### ISSUE THREAD

**Issue by IvanXIvanov881** [luchob/softuni-spring-may-2024#31]
**
при стартиране на проекта, отваряне на нов браузър и директен опит да достъпим примерно http://localhost:8080/offers/2
получавам тази грешка:

Caused by: java.lang.IllegalStateException: Cannot create a session after the response has been committed

**Comment by luchob** [comment]
Става въпрос за нашия проект ли?

**Comment by IvanXIvanov881** [comment]
да, пробвай да стартираш сървъра , след това отвори браузър и вкарай директно http://localhost:8080/offers/2 , би трябва да върне тази грешка в конзолата:

Caused by: java.lang.IllegalStateException: Cannot create a session after the response has been committed

порових се в нета, има доста писано за този exception. но не видях нещо, което да помогне при нас

Нещо има проблем с Api-то на exchange-a , ще потърся още малко проблема локално при мен и ще пиша пак, благодаря.

**Comment by IvanXIvanov881** [comment]
https://github.com/IvanXIvanov881/MotorcycleBG

**Comment by luchob** [comment]
Здравей, погледни и един подобен проблем :-)

https://github.com/luchob/softuni-feb2023/issues/104

Може да е жокер.

Поздрави и ще чакам фийдбек,
Л.

**Comment by luchob** [comment]
Затварям заради неактивност, ако има още проблем - отвори го наново.

Поздрави,
Л.
