### ISSUE TITLE
Въпрос относно Post Request към Rest Api

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#32]
**Опишете грешката**

Здравейте , за моя проект съм направил рест , в който се запазват различни crossfit - events и всеки user на сайта може да прави пост заявка , за да добавя event. Проблема обаче е , че ако искам да пазя евентите с id UUID при пост заявката получавам грешка , която не мога да разбера защо става :  Incorrect string value: '\xCC\xF8B\x9F\xD2\xC3...' for column 'id' . Заявката стига до реста , но при персиста на самото ентити в базата излиза тази грешка. Пробвах да сетвам и рандом ууид на ентито , което ще подавам към реста , но нищо не стана. Успях все пак да фиксна нещата , като направих идто да е Long , но може ли да обясните защо това се получава с UUID ? Четох и в stackoverflow , но там предложенията също не оправиха проблема. Благодаря предварително за отговора !

**Comment by luchob** [comment]
Здравей! Как точно си имплементирал UUID генератора в event entity-to? Може ли да комитнеш коментиран код за да мога лесно да репродуцирам проблема?

Поздрави,
Л.

**Comment by baldzhiyski** [comment]
Преди да го променя на лонг изглеждаше ето така : 
![Screenshot (60)](https://github.com/user-attachments/assets/815ba0d4-dcfb-414c-853e-606bd72ccfcf)
Също през заявка от postman отново излизаше същата грешка

**Comment by luchob** [comment]
Здравей, предполагам - получава се проблем (макар и да не мога да го репродуцирам) защото по подразбиране UUID-то се записва в binary поле в базата. За да проработи трябва да му подскажеш да го запазва в стринг, например ето така:

``` 
public class BaseEntity {

    @Id
    @GeneratedValue (generator = "uuid-hibernate-generator")
    @GenericGenerator(
        name = "uvid-hibernate-generator",
        type = org. hibernate.id.UUIDGenerator.class
    )
    @JdbcTypeCode(Types.VARCHAR)// <--- varchar!
    private UUID id;
}
```

После в DTO-то:

```
public class EventDto {

    private UUID uuid;
    private String address;
    private String eventName;
    private String description;
    private Date date;

    private String videoUrl;

}
``` 

Накрая самия успешен рикуест в `curl` формат:

```
curl --location 'http://localhost:8082/crossfit-community/events/publish' \
--header 'Content-Type: application/json' \
--data '{
    "address": "Sofia",
    "eventName": "XYZ",
    "description": "test",
    "date": "2024-07-06",
    "videoUrl": "http://localhost"
}'
``` 

Поздрави,
Л.
