### ISSUE TITLE
IT изтрива базата данни?

### ISSUE THREAD

**Issue by mr-pachev** [luchob/softuni-spring-may-2024#34]
*Връзка към проекта:* - https://github.com/mr-pachev/hrm-users.git

*Кратко описание:*
Здравей, Лъчо.

Днес се опитах да приложа показаните от теб integration testing за тест на Rest Controller в моят проект. Мисля че стана, НО с един нежелан ефект -> след страртиране на ItelliJ в тест режим и приключването й, базата данни се занулява. 
Насочих вниманието си към:  @AfterEach
                                                  public void tearDown() {
                                                      employeeRepository.deleteAll();
                                                 } 
но без нея се получава дублиране на резултатите и теста не минава. 

След съвет от ChatGPT-то направих следното:
- премахнах @AfterEach
                      public void tearDown() {
                      employeeRepository.deleteAll();
                     } 
- добавих към @SpringBootTest
                         @AutoConfigureMockMvc
                         и
                         @Transactional на самият клас.

Не знам дали е удачно, но тестовете митават без да изтриват базата.
Ако може да погледнеш и да дадеш становище по въпроса, защо отново при мен не се получава :-D

Отново благодаря предварително.

**Comment by luchob** [comment]
Здрасти!

:-) Идеята беше изобщо да не се връзва към истинската база данни, а по-скоро към in-memory (hsqldb). За да стане това, трябва да имаш в **test** папката тестово application.yaml което ще се използва вместо истинското. Разгледай това [тук](https://github.com/luchob/softuni-spring-may-2024/blob/main/mobilele/src/test/resources/application.yaml).

Между другото най-скъпия бъг, който съм виждал (щети за почти **7** цифрена сума) се получи заради integration test, който изтри production база :-)

Поздрави,
Л.

**Comment by mr-pachev** [comment]
:-D Дааа, доста неприятно е. 
Това са зависимостите, които ни трябват за работа с in-memory:
build.gradle:
testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
testRuntimeOnly 'org.hsqldb:hsqldb'
нали? 
В yaml-файла не успях да се ориентирам, кои настроики ни трябват за IT.

**Comment by mr-pachev** [comment]
Явно нещо не разбрах, отново ми изтрива базата.
build.gradle:
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'com.mysql:mysql-connector-j'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'com.maciejwalkowiak.spring:wiremock-spring-boot:2.1.2'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testRuntimeOnly 'org.hsqldb:hsqldb'

	implementation 'org.modelmapper:modelmapper:3.1.1'
	implementation 'org.springframework.security:spring-security-crypto:6.2.1'
}

yaml:
spring:
  application:
    name: hrm-users
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
Трябва ли задължително да имаме папка resources в test?

**Comment by luchob** [comment]
Здравей!

Да, трябва да е в resources иначе няма да го намери. Точно както е в mobilele.

Поздрави,
Л.
