### ISSUE TITLE
Проблем с DeleteMapping

### ISSUE THREAD

**Issue by reniangelovaa** [luchob/softuni-spring-may-2024#35]
https://github.com/reniangelovaa/BookWorld/tree/master
*Кратко описание:*
В ShoppingCartController, който съм анотирала с @RestController, имам метод анотиран с DeleteMapping за премахване на даден продукт от количката. В HTML-a cart.html също съм сложила метод DELETE, опитах и th:method="delete". Но когато натисна бутона  Remove, при инспектиране в браузъра получавам:

1 requests
361 B transferred
Request URL:
http://localhost:8080/api/cart/remove/1
Request Method:
POST
Status Code:
204 No Content
Remote Address:
[::1]:8080
Referrer Policy:
strict-origin-when-cross-origin

В IntelliJ не ми гърми нищо.

**Comment by luchob** [comment]
Здравей!

Предполагам, че проблемът се състои в това, че не ти се вика `DeleteMapping`-a, нали? Това е така, защото HTML формите поддържат единствено GET и POST заявки. Не съществува такова нещо като форма с DELETE mapping. Затова Spring/thymeleaf правят една малка имама (или по нашия си жаргон - hack). 

Трябва във формата да добавиш `th:method="DELETE"` а не само `method=DELETE`. 
```
<form th:action="@{/api/cart/remove/{id}(id=${item.id})}" th:method="DELETE">
                        <button type="submit">Remove</button>
                    </form>
```
Това нещо по време на rendering-a на формата ще генерира един скрит input параметър в нея и вместо DELETE формата ще стане POST. Нещо такова ще е резултата:

```
<form action="/api/cart/remove/1" method="POST">
    <input type="hidden" name="_method" value="delete">
     <button type="submit">Remove</button>
</form>
```

В настройките си в `application.yaml` имаш следния snippet:

``` 
  mvc:
    hiddenmethod:
      filter:
        enabled: true
``` 

Това нещо инсталира един филтър, който ще прихване POST заявката и ще я промени на DELETE. Така ще се извика и DeleteMapping-a. 

Надявам се това да помогне.

Поздрави,
Л.
