### ISSUE TITLE
Бъг относно IT за REST API

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#36]
*Връзка към проекта:*

[връзка](https://github.com/baldzhiyski/Crossfit-Web-App/commit/dd7f172d3afb92879ee3f13171267d1bc8c742ff)

*Кратко описание:*

Здравейте, след като изгледах лекцията за тестовете , реших да направя няколко , но изникна проблем. Когато се опитна в самия тест да персистна дадено ентити ми излиза следната грешка  : 

![Screenshot (68)](https://github.com/user-attachments/assets/02b2edf8-3069-453a-9d78-4c276faaa50f)

Това се случва като използвам следния yaml в ressources в папката test : 
![Screenshot (66)](https://github.com/user-attachments/assets/18686c64-2ba8-49b1-845d-3133947752e1)

В интернет намерих нещо , с което успяха да проработят нещата , но нямам идея защо и как при вас няма нужда от такова нещо. За да проработи това персистване промених yaml по следния начин : 
![Screenshot (65)](https://github.com/user-attachments/assets/b32471cf-bac7-4622-a4ec-83e12d176bc3)

Може ли да обясните защо проблема с персистването на ентити се получава без тези допълнителни неща в yaml файла ? Този проблем се случи и в другия проект . Оставил съм урл към комита . Там съм сложил новия yaml file .

Проблем номер 2 : 
Също още един проблем при ИТ тестовете , опитвам се да дествам например пост заявка , за която трябва някой да бъде логнат и да има роля USER  , например в WorkoutControllerTestIT се опитвам да нарпавя тест за писането на коментар. Бихте ли погледнали двете ми идеи за имплементация на теста ? И двете обаче редиректват към /access-denied страницата вместо към определената от мен. Оставям линк към  този комит тук : https://github.com/baldzhiyski/Crossfit-Web-App/commit/b83d722100b5e6f83fd3ce227e5eafe17c5214d6

**Comment by luchob** [comment]
Здравей!

Обяснението относно първият ти проблем. In-memory DB-то е съвсем различна база данни от MySQL. И то е RDBMS, но понякога с малко по-различен синтаксис, типове колонки и др. С други думи, ако сложиш нещо MySQL специфично в проекта има вероятност да не работи съвсем добре. Например, там няма колонка TEXT, а ти си сложил такава:

```
    @Column(columnDefinition = "TEXT")
    @NotBlank
    private String description;
``` 

Та с това  `columnDefinition = "TEXT"` с приключил с независимостта от базата. Оправил си го, като си настроил HSQLDB-то да работи в съвместим с MySQL режим.

**Comment by luchob** [comment]
Относно втория проблем, да бих ти дал идея. Импортни стартера за тестване със спринг секюрити:
```
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-test</artifactId>
    <scope>test</scope>
</dependency>
```

След това ползвай анотацията `@WithMockUser`. Детайли [тук](https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/test-method.html#test-method-withmockuser).

Поздрави,
Л.

**Comment by baldzhiyski** [comment]
Благодаря ви ! За коментарите един от проблемите беше също , че ми липсваше csrf . Предполагам при повечето пост завки е необходим .

**Comment by luchob** [comment]
Да, spring security автоматично добавя csrf защита, затова е необходимо да се сложи csrf() на mockMvc-то.

Поздрави,
Л.
