### ISSUE TITLE
Прикачване на файл/снимка

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#37]
Здравей, Лъчо, имам няколко проблема с проекта: 

1. Опитвам се да направя така, че в RecipeControllera да мога да прикачвам снимка при добавянето на рецепта, но дори да избера файл ми дава грешка, че не съм избрала. Изписва ми проблем, че не може да конвертира Multipart file to String, каквото реално ми е полето за image. Следвам инструкциите, които Банкин ни беше показал в предния курс, но не сработва.
2. Интересува ме също така ако искам да си напълня базата с рецепти в data.sql файла как трябва да вкарам картинките? Пробвах с LOAD_FILE('/images/example.png), но не сработва
3. На nav bar-a имам линкове към логин и реджистър. Ако натисна register ме препраща към register формата, след това ако натисна логин ме препраща на логин формата и като отново опитам да достъпя register не ме препраща, а си оставам на login. Каква е причината?

https://github.com/BogoevaPetya/DeliciousRecipes

Поздрави,
Петя

**Comment by BogoevaPetya** [comment]
@luchob Тагвам те в случай, че issue-то не е достигнало до теб

**Comment by luchob** [comment]
Здравей, Петя!

**Относно 1)** Не виждам как ще успееш да мапнеш файла към стринг. Трябва да бъде `MultipartFile image`. Бях правил едно демо проектче, можеш да го свалиш или да го разгледаш [тук](https://github.com/luchob/fileupload).

Освен това контролера ме учудва:

```
                            @Valid RecipeAddDTO recipeAddDTO,
                            @RequestParam("image")MultipartFile file,
                            BindingResult bindingResult,
                            RedirectAttributes redirectAttributes,
                            @AuthenticationPrincipal UserDetails userDetails
```

Тук виждам, че имаш хем image в recipeAddDTO, хем в `RequestParam`. Предлагам ти, да изтриеш този `RequestParam` и да смениш типа в `RecipeAddDTO`. Самата реализация на записа във ДБ също изглежда не е съвсем готова. В допълнение искам да отбележа, че ако `BindingResult` параметъра не стои непосредствено след параметъра анотиран с `@Valid`, валидацията ще гръмне преди да се изпълни метода и сървъра ще върне грешка 400.

**Относно 2)** Ако използваш blob поле, един елементарен но и малко грубичък начин е да обърнеш файла на hex string. Виж отговорът [тук](https://stackoverflow.com/questions/10729824/how-to-insert-blob-and-clob-files-in-mysql)  и малко в [документацията на mysql](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_hex).

Има разни тулове в нет-а, които ще ти помогнат - напр [този](https://tomeko.net/online_tools/file_to_hex.php?lang=en )(оттикни и твата чекбокса).

**Относно 3)** Тук грешката е по-елементарна. Използвала си релативно URL вместо абсолютно.

Зле -> `th:href="@{users/register}"`
Добре -> `th:href="@{/users/register}"`

Разликата е че първото, както подсказва името му е релативно на текущия ти път. И като отидеш на `/users/login`, регистър линка става `/users/users/register`. Което пък е забранено и те отвежда обратно на login страницата.

Поздрави,
Л.
