### ISSUE TITLE
Проблем с UserDetails

### ISSUE THREAD

**Issue by NikolaySHA** [luchob/softuni-spring-may-2024#38]
*Връзка към проекта: 

https://github.com/NikolaySHA/ExclusiveService

*Кратко описание:*

Здравей, тотално се омазах при рефакторирането на  ExclusiveUserDetails и сървиза за него.  Сега когато съм логнат все още мога да достъпя адреса на логин формата, както и юзър, който не е АДМИН, може да достъпи до адреса на  admin-panel. В предишни комити си работеше добре, но имах един UserDetailsHelperService, който беше в повече мисля. Моля за съдействие.  Благодаря!

**Comment by luchob** [comment]
Здравей!

Чак пък омазване... Това, че можеш да видиш логин страницата, когато си логнат не е security проблем ако се замислиш. Откъм UI/UX си ОК, защото нормалния юзър не я вижда в юзър интерфейса. А потенциалния зловреден юзър дори и да я види, не може да направи нищо лошо с нея. Затова и спринг не предоставя конфигурация която да забранява страници за аутентицирани юзъри.

Относно `/admin-panel`, обаче - проблем действително има. Ако искаш да я забраниш с `@PreAuthorize` както си направил:

``` 
    @GetMapping("/admin-panel")
    @PreAuthorize("hasRole('ROLE_ADMIN')")
    public String loggedIn(@AuthenticationPrincipal UserDetails userDetails, Model model) {
    
``` 

Трябва да добавиш още една анотация върху апликацията. Тя се нарича `@EnableMethodSecurity`. Ето така:

``` 
@SpringBootApplication
@EnableMethodSecurity
public class ExclusiveServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(ExclusiveServiceApplication.class, args);
    }
}
``` 
Ако пък искаш да я конфигурираш на ниво HttpSecurity, трябва да добавиш ред. Ето така:

```
  .requestMatchers("/", "/users/login", "/users/register", "/gallery","/users/login-error", "/contacts", "/services").permitAll()
  .requestMatchers("/admin-panel").hasRole("ADMIN")
```

Поздрави,
Л.

**Comment by NikolaySHA** [comment]
Благодаря ти!  Сложих една проверка в контролера:
        if (userService.findLoggedUser() != null) {
            return "redirect:/home";
        }
        return "login";
    } 
    и вече всичко работи...

**Comment by NikolaySHA** [comment]
Здравей, извинявам се за безпокойството, но имам няколко главоблъсканици за решаване и моля за съдействие.
1. не мога да накарам валидациите на EditDTO-тата да заработят при никакви обстоятелства.
2. търся начин да визуализирам датата от подаденото DTO(датата е сетната правилно от модел мапера)във формата в edit-appointment.html
3. Има ли начин да имплементирам логика с която да пресметям за всяка седмица капацитета от записани детайли и спрямо това да показвам на клиента в календара кога е следващата свободна дата за записване при създаване или промяна на апойнтмента?
Много ти благодаря!

**Comment by luchob** [comment]
Здравей!

1. Валидацията работи в рамките на контролера, тъй като връща коректно всички грешки спрямо анотациите. Но ти правиш редирект и там където редиректваш няма никакъв код който да визуализира тези грешки. Още повече, че съставяш и някакво съвсем ново и различно DTO. Правя copy&paste от нашия проект за да напомня как обработвахме грешки:

```
  @GetMapping("/add")
  public String newOffer(Model model) {

    if (!model.containsAttribute("addOfferDTO")) {
      model.addAttribute("addOfferDTO", AddOfferDTO.empty());
    }

    return "offer-add";
  }

  @PostMapping("add")
  public String createOffer(
      @Valid AddOfferDTO addOfferDTO,
      BindingResult bindingResult,
      RedirectAttributes rAtt) {

    if(bindingResult.hasErrors()){
      rAtt.addFlashAttribute("addOfferDTO", addOfferDTO);
      rAtt.addFlashAttribute("org.springframework.validation.BindingResult.addOfferDTO", bindingResult);
      return "redirect:/offers/add";
    }
   ...
}
```

И в thymeleaf-a:

``` 
<small th:each="err : ${#fields.errors('description')}" th:text="${err}" class="text-danger"></small>
``` 

2. В thymeleaf:

``` 
            <input type="date"
                   class="form-control"
                   id="date"
                   name="date"
                   th:field="*{date}"
                   th:errorclass="'is-invalid alert-danger'">
            <small th:errors="*{date}" class="invalid-feedback text-danger"></small>
``` 

После добави на датата следната анотация:

```
import org.springframework.format.annotation.DateTimeFormat;

    @DateTimeFormat(pattern="yyyy-MM-dd")
    private LocalDate date;
``` 

3. Разбира се, че има. Вземаш текущата дата, смяташ първия и последния ден от седмицата. С `@Query` анотация в репозиторито съставяш JPQL query и смяташ броя на детайлите за седмицата. След това смяташ свободните занапред, като отново правиш query. Нещо подобно, мисля че не е чак толкова трудно да се измисли.

Поздрави,
Л.

**Comment by NikolaySHA** [comment]
Здравей отново, искрено ти благодаря за съдействието и бързите отговори, порефакторирах и кое разбрах, кое не, ама вече що годе работи по план. Обаче немога да подкарам по никакъв начин могъл бутона за навигацията при малък дисплей, самия бутон, мога да го стилизирам със !important  в ц-сс-а, обаче не става нищо при натискане, опитвах да импортна разни цсс и линкове директно в хтмл-а без успех. а най интересното е че работеше в един момент. Ако имаш време да удариш още едно рамо. Благодаря ти отново!

**Comment by luchob** [comment]
Здрасти!

И на мен преди месец в селската къща ми спря осветлението в хола. А най-интересното е, че работеше. :-) И съседа ми - ел. техник и донякъде житейски мъдър - ми даде насоки как най-лесно се открива проблема в случая, като ме попита - "кажи ми какво се промени в къщата днес?" Замислих се и почти през сълзи му казах "пробивах дупки за корниз...". С подобна информация може да извадиш дебъгера и да дебъгнеш...

<img width="274" alt="Screenshot 2024-07-27 at 15 27 14" src="https://github.com/user-attachments/assets/ed7c5676-e072-46d2-a4d2-e9b3d76ea67e">


Та така и при теб. Когато нещо е работило, а вече не, поглеждаш хисторито в github:

<img width="560" alt="Screenshot 2024-07-27 at 15 19 12" src="https://github.com/user-attachments/assets/6578d6b6-5028-46cc-b2fa-24c670dbd362">

Върнах ти промените от този комит и отново работи тогъл бутона:

<img width="487" alt="Screenshot 2024-07-27 at 15 18 49" src="https://github.com/user-attachments/assets/f770f05b-b3d2-4816-8057-9843b9865fb0">

Поздрави,
Л.

**Comment by NikolaySHA** [comment]
Здравей, съжалявам че те безпокоя през отпуската, но голям проблем :D... Опитах се да кача 3 те имиджа(основното ми приложение, изнесената част(https://github.com/NikolaySHA/ExpensesAPI) и MySql) в контейнер и да ги подкарам през докер. На пръв поглед се получава, обаче като отида на даден апойнтмент и хвърля грешка, че няма мапинг. Не мога да го дебъгна и разшифровам в браузера, но вероятно е някоя настройка в yaml и не сработва заявката от основното ми приложение за извличане на разходите по съответния апойнтмент. Моля за съдействие, когото е удобно. Това е dockerhub-a ми: https://hub.docker.com/repositories/nikolaysha(ако е нужен) Благодаря!

**Comment by luchob** [comment]
Здравей, ако ги подкарваш през докър най вероятно използваш docker compose файл. Или поне го пускаш с някакви команди. Така че са ми необходими тези детайли, за да ти съдействам.

Поздрави,
Л.

**Comment by NikolaySHA** [comment]
Добро утро. 
version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ROOT_USERNAME=db
      - MYSQL_ROOT_PASSWORD=Niki860115

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  exclusive-service:
    depends_on:
      db:
        condition: service_healthy
    image: nikolaysha/exclusive-service
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Niki860115
      - ***@***.***
      - MAIL_SENDER_PASSWORD=Niki860115
      - EXPENSES_BASE_URL=http://expenses-api:8081
  expense-api:
    depends_on:
      db:
        condition: service_healthy
    image: nikolaysha/expenses-api
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Niki860115

Това ми е docker-compose файла, MySQL не трева на 3306 и затова го пускам на 3307, но не мисля че в това е проблема...

**Comment by luchob** [comment]
URL-то, което си конфигурирал е:
```
- EXPENSES_BASE_URL=http://expenses-api:8081
``` 

А сървиса е:
```
  expense-api:
``` 

Т.е. липсва едно s или горе е в повече едно s. => не може да се резолвне URL-то.


Поздрави,
Л.

**Comment by NikolaySHA** [comment]
Сигурен бях, че е нещо подобно. Много ти благодаря!Sent from my iPhoneOn 6 Aug 2024, at 12:45, Lachezar Balev ***@***.***> wrote:﻿
Closed #38 as completed.
