### ISSUE TITLE
Validation Via Custom Annotation

### ISSUE THREAD

**Issue by ttheconjuring** [luchob/softuni-spring-may-2024#4]
Връзка към проекта: https://github.com/ttheconjuring/TestingEz

Кратко описание:
Направих си custom annotation "NotTaken", която просто проверява дали даден username, email или phone вече съществува в базата. Поставям я на полета "username", "email", "phone" в DTO-то за регистрация на потребител.

Възможно най-накратко опишете:

Не знам дали имам проблем или нямам, защото го правя за първи път. Не знам дали е добра идея да правя такава анотация или по-добре ще е, ако си направя проверките в бизнес логиката. Просто желая да чуя обратна връзка по този въпрос.

Въпроси:
Трябва ли да има анотация или не?
Така ли се имплементира custom анотация?
Защо в клас NotTakenValidator.java @AllArgsConstructor не ми маха конструктора, а във всеки друг клас го прави?

Благодаря предварително!

**Comment by luchob** [comment]
Здравей!

Не съм на мнение, че имаш проблем. Ето какво си мисля за подхода - custom validator vs бизнес логика:

**С custom validator:**

**Плюсове:**

- разделение на логиката - валидатора се занимава само с валидация, за разлика от сървиса
- лесна преизползваемост - в твоя случай май не важи особено много :-)
- по-четим код - валидациите са разположени в лесно четими анотации, които разбираш от пръв поглед
- по-лесно тестване

**Минуси:**

- по-сложните валидации се нуждаят от доста депендънсита, което може лесно да превърне валидатора в голям сървис

**В сървис layer-a:**

**Плюсове:** 

- всичките ти необходими депендънсита и допълнителна логика са там.
- сърнис лейъра е зает с бизнес логиката, така че по-сложната валидация сякаш принадлежи там

**Минуси:**

- трудно за преизползване в други контексти
- по-трудно тестване
- по нечетим код

В заключение - бих препоръчал валидатори в случаи на проста или умерено сложна валидация и сървис лейър в останалите случаи.

Относно ` @AllArgsConstructor ` - мисля, че прави това защото имаш две мембър полета:

```
    private final UserRepository userRepository;
    private String fieldName;

    public NotTakenValidator(UserRepository userRepository) {
        this.userRepository = userRepository;
    }
``` 
` @AllArgsConstructor ` ще се опита да създаде още един конструктор с аргументи `userRepository` и `fieldName` което ще резултира в един клас с два различни конструктора, което не е проблем за ломбок и java.

Поздрави,
Л.

**Comment by ttheconjuring** [comment]
Благодаря за изчерпателния отговор, но не разбирам защо казвате "лесна преизползваемост - в твоя случай май не важи особено много :-)".
Подозирам, че го казвате, защото анотация работи само за три полета от таблица users и няма да работи за проверка на други полета в други DTO-та. Ако съм прав, може само да ми реагирате :D Благодаря отново

**Comment by luchob** [comment]
Да, точно туй исках а кажа. NotTakenValidator може да се използва само в твоя проект върху твоя юзър и то само върху някои полета. Което не винаги е толкова лошо. Въпросът е малко философски, но щом работи и не е прекалено грозно, значи е ок. Ако отвориш кода на спринг ще видиш далеч по-страшни неща ;-)

Поздрави,
Л.

**Comment by ttheconjuring** [comment]
Благодаря, Лъчо! Рефакторирах кода и вече може да се използва на всички полета във всички класове.
