### ISSUE TITLE
Проблем с файла за  интернациолизацията.

### ISSUE THREAD

**Issue by Aleksandra-Ilieva** [luchob/softuni-spring-may-2024#40]
Здравейте, 

Имам проблем с интернациолизацията на проекта ми, всичко работи, настроила съм всичко да е с UTF8, но най-отодолу, в Intellij ми показва че UTF8 e (disabled for properties), но реално си разпознава българските символи в  messages_bg.properties 
и си работи, когато сменям езика, но когато push-на промените, файла ми се кодира и в github изглежда така:
"offer.emergencyCare=\u0421\u043F\u0435\u0448\u043D\u0430 \u043C\u0435\u0434\u0438\u0446\u0438\u043D\u0441\u043A\u0430 \u043F\u043E\u043C\u043E\u0449" 
След това се променя и в проекта ми, като продължава да си работи, но излиза по този начин,  а ако ръчно променя файла в гитхъб няма проблем и си изглежда нормално с български символи. Също ако не го push-на   пак си седи с българските символи, тоест променя се след push и изглежда по този начин и локално и в github.

**Comment by luchob** [comment]
Здравей!

Най-вероятно си цъкнала `Transparent native-to-ascii conversion` когато си настройвала всичко да е в UTF-8 в `Editor > File encodings`.

Ако не е така, отвори наново този бъг или пиши в него.

Поздрави,
Л.
