### ISSUE TITLE
Задаване на роля

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#41]
Имам въпрос относно ролите, ще имаме ли възможност  на някоя лекция да отделим време за тях?
Как да задам роли в проекта: с sql ли да ги напълня или има и по-добър начин.?
Освен това в някои проекти забелязвам, че като ги дръпна и в базата данни винаги стои един потребител, който е админ, но него не виждам как сме го задали като такъв, поне в data.sql-a не е със сигурност. Може ли да обясниш как да си създам такъв потреител, който винаги да е в базата и да е админ.

**Comment by luchob** [comment]
Здравей, прочетено e, надявам се да намеря време :-)

**Comment by luchob** [comment]
Здравей!

Вчера предложих вариант -> https://github.com/luchob/softuni-spring-may-2024/blob/main/mobilele/src/main/java/bg/softuni/mobilele/config/AppConfig.java#L25

Поздрави,
Л.
