### ISSUE TITLE
Pageable 

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#43]
*Връзка към проекта:*
 [връзка](https://github.com/baldzhiyski/Crossfit-Web-App) 

*Кратко описание:*

Здравейте , имам въпрос относно как точно мога да направя pageable . В about-us страницата дърпам от рест , който аз съм направил , 3 евента . Това което искам да направя , е да дръпна всички евенти и да направя Pageable , за да може всеки да вижда всички от тях , като искам да се показват на всяка страница по 3  евента.
Така изглежда метода , който взима всички евенти от реста. 
![Screenshot (82)](https://github.com/user-attachments/assets/3a651567-b031-4bfb-8283-88e99b1216b9)

Така изглежда и самия респонсе , който връща реста : 
![Screenshot (83)](https://github.com/user-attachments/assets/f4637fd9-b000-4068-a36f-e327625200ac)

Трябва ли да направя самия рест да връша Pageable  или мога някак си когато дърпам бодито на респонса да направя нещо друго ? В интернет видях като идея да сменя самия респонс в реста  , но след това не знам как точно трябва да обработя данните които дръпна от там. Бихте ли ми казали кой би бил най-лесният начин в този случай да направя Pageable на евентите в about-us страницата ? 
Благодаря предварително за помощта !

**Comment by luchob** [comment]
Здравей! 

В новия спринг (след 3.3.0 вкл. мисля) има нови нещица за пейджовете. Ок, да опитаме. Първо две неща:

`Page` наричаме един подсписък с обекти.
`Pageable` пък - информация за пейджинга - размер, офсет, сортировка.

От сървъра лесно би могъл да връщаш Page или сериализируемия вариант - PageModel.
```
  @GetMapping
  public ResponseEntity<Page<OfferDTO>> getAllOffers(@PageableDefault(
      size = 3,
      sort = "id",
      direction = Direction.ASC
  ) Pageable pageable) {
    return ResponseEntity.ok(
        offerService.getAllOffers(pageable)
    );
  }
```

```
  @GetMapping
  public ResponseEntity<PagedModel<OfferDTO>> getAllOffers(@PageableDefault(
      size = 3,
      sort = "id",
      direction = Direction.ASC
  ) Pageable pageable) {
    return ResponseEntity.ok(
        new PagedModel<OfferDTO>(offerService.getAllOffers(pageable))
    );
  }
```

Ако избереш първия вариант, Spring ще ти каже за Page e интерфейс, а PageImpl е това което се опитваш да върнеш а това е клас който не е "stable" затова ще се наложи да сложиш една анотация, която самия спринг ще ти подскаже в логовете.

От страна на клиента можеш да си направиш едно DTO:

```
public class PageResponse<T> {
  private List<T> content;
  private PageMetadata page;

  @NotNull
  public List<T> getContent() {
    return content != null ? content : List.of();
  }

  public PageResponse<T> setContent(List<T> content) {
    this.content = content;
    return this;
  }

  public PageMetadata getPage() {
    return page;
  }

  public PageResponse<T> setPage(PageMetadata page) {
    this.page = page;
    return this;
  }
}
``` 
И да консумираш API-то горе долу така:

```
  @Override
  public Page<OfferSummaryDTO> getAllOffersSummary(Pageable pageable) {
    LOGGER.info("Get all offers...");

    PageResponse<OfferSummaryDTO> offers = offerRestClient
        .get()
        .uri("/offers?page={page}&size={size}&sort=id,desc",
            pageable.getPageNumber(),
            pageable.getPageSize()
        )
        .accept(MediaType.APPLICATION_JSON)
        .retrieve()
        .body(new ParameterizedTypeReference<>(){});

    assert offers != null;

    return new PageImpl<>(offers.getContent(), pageable, offers.getPage().totalElements());
  }
```

Вероятно примера е непълен и е нужно допълнително ровичкане, но това са насоките горе долу :-) Не е твърде елементарно, за съжаление.

Поздрави,
Л.

**Comment by baldzhiyski** [comment]
Здравейте , мисля , че успях да го направя , поне ми връща правилен резултат , но визуализацията ми е доста зле . Всеки път като цъкна върху Next или Previous се презарежда страницата . Евентите се променят , но това презареждане на цялата страница изглежда доста зле. Опитах и други неща , в интернет прочето да го направя с ajax  , но нищо не се получи. Има ли някакъв по-лесен начин за по добра визуализация без презареждане на цялата страница ? https://github.com/baldzhiyski/Crossfit-Web-App/commit/084e333b7e766f34474f366c3f4d44a2d1ae66b8 . 
В about - me  template - a е и самия Pagination.

**Comment by luchob** [comment]
Здравей!

Лесен начин без много JS и без презареждане не мисля, че има. Може да пробваш, да генерираш само част от страничката и да я презареждаш с JS но... пак няма да е съвършено тривиален. В angular например, в материал дизайн си има съпорт за paging но тук работим със сървър side rendering => или много JS или reload :-)

Поздрави,
Л.
