### ISSUE TITLE
Идея за Prometheus Grafana

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#44]
Здравейте , изгледах видеото от миналото издание за Deployment Hosting Monitoring и ми стана интересно ако използваме реално grafana и prometheus и искаме да следим например колко често се разглежда дадена страница или колко често някой се регистрира в системата как може ако имаме дадена html  страница , например dashboard , която ще е предназначена за админ , и да визуализираме резултатите от графана. Ако остане време би било добре ако може да ни покажите някое кратко демо за въведение. Също в лекцията за Deployment ще бъде ли възможно ако използваме Azure за deploymenta както в миналото издание да ни покажете  как реално можем да свържем и докер файла , който имаме ?

**Comment by luchob** [comment]
Привет!

Всъщност, графана е инструмента за визуализация на данните от прометеус и идеята е да бъде отделно приложение, до което администраторите и девелопърите да имат достъп. При нас се използва често и бяхме направили дори едно демо (там малко бях глътнал бастуна :-) ):

https://www.youtube.com/watch?v=US8UqEpywNg

В момента търся акаунт за Azure, там положението ми е много сериозно тъй като по принцип работя в GCloud и тези неща за които ме питаш мога да ги направя в контекста на Kubernetes/GCloud но не и Azure. Там ще съм благодарен ако успея просто да подкарам проекта, хаха :-)

Поздрави,
Л.
