### ISSUE TITLE
Unit and Integration testing

### ISSUE THREAD

**Issue by BlagoyVelinov** [luchob/softuni-spring-may-2024#45]
Здравей Лъчо, 
Имам питане отностно тестването с UnitTest. Когато се опитам да тествам void метод не се получава нищо, както и такъв който е зависим от друг като например в моя случай: имам метод createOrder(createOrderDto, username)-> когато се опитам да намеря user с този username ми гърми теста с nullUser, можеш ли да ме ориентираш как да тествам войд методи?

Също за integration testing, само на рест контролери ли се прави или може и на нормални контролери? Ако е възможно да се тестват нормални контролери ще можеш ли да покажеш един пример за тях?

https://github.com/4ukNoris/Spring-Project/tree/master

**Comment by luchob** [comment]
Здравей! 

За unit test-овете можеш да тестваш void методи с помощта на мокито (например аргумент капторите) за които говорихме. Отново, имаш три фази:

1. `Arrange` - setup-ваш всички необходими тестови данни и мокове, които ще се ползват от компонента, който тестваме.
2. `Act` - викаш метода, който ще се тества
3. `Assert`  - проверяваш дали всичко е както очакваш. 

Най-основен пример:

Трябва да тестваме това:

```
   @Override
    public void createUserOrder(OrderMovieDto createOrder, String username) {
        UserEntity user = this.userService.getUserByUsername(username);
        Order order = this.mapOrderMovieDtoToOrder(createOrder, user);

        if (order.getId() == 0) {
            this.orderRepository.save(order);
        }
    }
```

Трябва да подсигурим нещо връщано от мок юзър сървиса, да видим дали `mapOrderMovieDtoToOrder` e намапнал правилно данните и дали е извикано `orderRepository.save()`:

```
@ExtendWith(MockitoExtension.class)
class OrderServiceImplTest {
    private OrderServiceImpl toTest;
    @Mock
    private UserService mockUserService;
    @Captor
    private ArgumentCaptor<Order> orderEntityCaptor;
    @Mock
    private OrderRepository mockOrderRepository;
    @Mock
    private CityService mockCityService;


    @BeforeEach
    void setUp() {

        this.toTest = new OrderServiceImpl(
                this.mockOrderRepository,
                this.mockUserService,
                this.mockCityService,
                new ModelMapper()
        );

    }

    @Test
    public void testCreateUserOrder() {
        // Arrange
        OrderMovieDto orderMovieDto = createTestOrderMovie();
        UserEntity userEntity = createTestUserEntity();

        when(this.mockUserService.getUserByUsername(userEntity.getUsername()))
                .thenReturn(new UserEntity());
        when(this.mockCityService.getCityByCityName(orderMovieDto.getLocation()))
                .thenReturn(new City(orderMovieDto.getLocation()));

        // Act
        this.toTest.createUserOrder(createTestOrderMovie(), userEntity.getUsername());

        // Assert
        verify(this.mockOrderRepository).save(orderEntityCaptor.capture());

        Order actualOrder = orderEntityCaptor.getValue();

        Assertions.assertEquals(orderMovieDto.getLocation(), actualOrder.getCity().getLocation());
        // TODO: Add more assertions
    }

    private UserEntity createTestUserEntity() {
        UserEntity userEntity = new UserEntity();
        userEntity.setUsername("pesho");
        return userEntity;
    }
    private OrderMovieDto createTestOrderMovie() {
        OrderMovieDto orderMovieDto = new OrderMovieDto();
        orderMovieDto.setLocation(CityName.SOFIA);
        orderMovieDto.setProjectionDate(LocalDate.of(2022, 1,1));
        return orderMovieDto;
    }
}
```

Забележки:

Юнит тестовете не винаги са най-доброто решение за тестване на толкоз обширна функционалност.
Ако държиш на юнит тест и той ти се струва прекалено сложен, то обикновено е редно да разцепиш кода на по-малки компоненти.

**Comment by luchob** [comment]
Относно втория въпрос, на лекцията показахме пример за тест на нормален контролер. Провери ето [тук](https://github.com/luchob/softuni-spring-may-2024/blob/main/mobilele/src/test/java/bg/softuni/mobilele/web/RegistrationControllerIT.java).

Поздрави,
Л.

**Comment by BlagoyVelinov** [comment]
Много благодаря за помоща и бързия отговор. Мисля че пробвах подобен
вариант да тествам контролер но не иска да зареди самия тест. Ще пробвам
пак да тествам контолера и се надявам да се получи. Ако не стане ще ти
пратя грешката понеже в интернет не намерих решение. Благодаря отново!
Поздрави!

На ср, 17.07.2024 г., 16:59 ч. Lachezar Balev ***@***.***>
написа:
