### ISSUE TITLE
Какви Unit Test-ове могат да се направят за Helper Service? Допълнителен въпрос свързан с GitHub.

### ISSUE THREAD

**Issue by ChrisHartarski** [luchob/softuni-spring-may-2024#47]
*Връзка към проекта:*
https://github.com/ChrisHartarski/MagnaTechnica-WebShop-SoftUniProject

*Кратко описание:*

Възможно най-накратко опишете:

1. Unit Test-ове
Не знам какви тестове мога да направя за UserHelperService класа. Всички методи са обвързани с класове, които идват от Spring, което прави ситуацията доста оплетена за Unit тестове.
UserHelperService-a се намира в service/helper/
UserHelperService-а се използва предимно, за да извличам повече информация за логнатия user и да я подавам към други service-и и thymeleaf.
Може ли идеи какви тестове могат да се направят и как да се направи Mock-не principal-а, защото той присъства навсякъде?

2. GitHub
Предстои ми да направя допълнителен service, който да е на отделен сървър и да си комуникират с REST. Този допълнителен проект знам как да го направя в ново репозитори в GitHub. Има ли начин да направя parent folder в сегашното ми GitHub repository, който folder да съдържа и двата проекта.
Ако може, как точно трябва да се изпълни това, без да губя commit-ите към момента.

*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които бързо може да се репродуцира проблемът.

**Comment by luchob** [comment]
Здравей!

Не всичко е удачно или дори възможно да се тества с Unit test. Например, статични извиквания като това просто не са тестваеми с unit tests:

```
SecurityContextHolder.getContext().setAuthentication(authentication);
``` 

Бих оставил покритието на точно тези неща на интегрейшън тестовете.

Относно допълнителния сървис и двете опции са валидни. Можеш да бъде в отделно репозитори или пък в папки, точно както аз си го правя. Може и в multi project gradle build, но това е доста по сложно. Предполагам, че ме питаш защото не искаш да си изгубиш комитите в репозиторито. Не бих се притеснявал за това защото комитите са за това - за да не можеш да ги изгубиш при каквито и да е размествания. Веднъж там си остават там и можеш да не се притеняваш за изискванията за изпита.

Позддрави,
Л.
