### ISSUE TITLE
JS timer issue and weird browser behaviour

### ISSUE THREAD

**Issue by ttheconjuring** [luchob/softuni-spring-may-2024#48]
*Връзка към проекта:*

https://github.com/ttheconjuring/TestingEz

Имам страничка, която представлява въпрос с отговори за избиране. Всеки въпрос има време за реакция от страна на потребителя. Ако не отговори сам, отговорът му се записва автоматично и се преминава към следвашия въпрос. При презареждане на страницата, таймерът се рестартира, а това не трябва да се случва. Също така има и логика за превенция срещу връщане към вече отговорен въпрос, но винаги след 3-4 опита за връщане назад, логиката започва да се игнорира и сякаш браузърът започва да действа на своя глава и ме връща не страничката, от която мога да стартирам теста и да отговарям на въпросите.

1. Какво очаквам да се случи
- Очаквам да не мога да се върна назад или където и да било, докато не отговоря и на последния въпрос от теста.
- Очаквам таймера да не се рестартира, всеки път като страницата се презареди или ме redirect-не към нея.
2. Какво всъщност се случва
- При повече от 3-4 опита за достъпване на вече отговорен въпрос, контролерите, които контролират процеса, започват да се игнорират. (при първите два опита, успешно се проверява дали потребител вече е отговорил на въпрос, към които се опитва да отиде, а после се игнорира и ме връща на страница, различна от тази за въпросите)

Описвам възможно най-лесните стъпки, с помощта на които бързо може да се репродуцира проблемът:
1. Регистрация 
2. Логване
3. Създаване на тест
4. Присъединяване към тест
5. Отговаряне на първи въпрос
6. Опит за връщане към първи въпрос 3-4 пъти

**Comment by luchob** [comment]
Здравей!

Таймерът се рестартира при рефреш по очевидната причина, че не помниш на сървъра кога е започнало показването на въпроса. За да можеш да не рестартираш таймъра, трябва при рефреш да сметнеш оставащото време на сървъра и да го върнеш с HTML-a към таймере. Без участието на сървъра, няма как да се случи продължаване на времето до където е стигнало след рефреш.

Относно другия въпрос се боя, че знам защо се случва, но не знам как да ти помогна :-) Много браузъри, в това число и хром имплементират евристични алгоритми, благодарение на които back бутона може да пропуска страници. Това е направено съвсем умишлено, защото когато попаднат на "лош" сайт много хора се опитват да го напуснат с back бутон. Ако това бъде блокирано (точно както ти се опитваш да направиш) те ще бъдат хванати "в капан" там и back бутона няма да може да ги изведе.

Поздрави,
Л.
