### ISSUE TITLE
Не ми логва User-a след имплементиране на Spring Security

### ISSUE THREAD

**Issue by tony9701** [luchob/softuni-spring-may-2024#49]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*

https://github.com/tony9701/propertiesApp

*Кратко описание:*

1. Какво очаквате да се случи

Очаквам да мога да се логна с вече регистриран юзър

2. Какво всъщност се случва

Не се логва

3. (Желателно) Какво опитахте

Дебъгвах и до колкото видях винаги имам ауторити anonymous тоест предполагам проблема
ми е нещо със ролите 

*Стъпки за репродуциране:*

пробвах да проследя целия процес, но всичко изглежда наред..
прегледах и вашия код не виждам някаква разлика съществена.

**Comment by luchob** [comment]
Здравей! 

Извинявай за бавния отговор. Проблемът изобщо не е в ролите. Когато дебъгваш, започни от network таба в dev tools на браузъра. Там ще видиш какво се праща към сървъра:

<img width="1344" alt="Screenshot 2024-07-20 at 11 17 21" src="https://github.com/user-attachments/assets/c50d4b72-ea61-43c8-83f2-20ad959029e2">

И ще се изненадаш, че нищо не се праща (освен csrf токъна) :-) Оттам нататък и нищо не може да се случи. 

Следваща стъпка е да установим защо не се праща нищо. Отваряме формата:

``` 
            <form th:method="post"
                  th:action="@{/login}">
            <div class="input-box">
                <input type="text" placeholder="Email"
                required>
                <i class='bx bxs-user'></i>
            </div>

```

Вижкаме имейл input-a. Той няма име и браузъра не би могъл да знае как да го изпрати по мрежата. Би трябвало да зададеш имена на контролите си, например:
```
                <input type="text" name="email" placeholder="Email". required>
```

Тогава вече би трябвало да тръгне по мрежата и да видиш дали работи.

Поздрави,
Л.

**Comment by tony9701** [comment]
Да, има логика. Много благодаря за подробния отговор, сега ще си поиграя да видим! Лек ден!
