### ISSUE TITLE
Проблем със Spring Security в проект

### ISSUE THREAD

**Issue by pako8101** [luchob/softuni-spring-may-2024#5]
*Връзка към проекта:*

https://github.com/pako8101/HistoryAppNewSpring2024

*Кратко описание:*

Привет, имам проблем със Security в моя проект, преди да вкарам Spring Security всичко работеше перфектно, имплементирах го както сте показали в предния курс всичко направих както казвате, но не сработва регистрацията и съответно логина. Това е от два месеца иначе вече щях да съм готов с крайния проект.
Благодаря 

p.s.
Изгледатл съм всички курсове назад, и съм направил всики проекти, но нещата се закучиха на Секюритито :)

**Comment by luchob** [comment]
Здравей!

Имаш бъг/проблем в `ApplicationUserDetailsService` и по-специално в това парче код:

```
private  UserDetails map(UserEnt userEntity) {

        return new AppUserDetails(
                userEntity.getUsername(),
                userEntity.getPassword(),
                extractAuthorities(userEntity)
        ).setAge(userEntity.getAge()).
                setFullName(userEntity.getFullName());

    }
```

Методът `setAge` на `AppUserDetails` изисква int:

```
public AppUserDetails setAge(int age) {
        this.age = age;
        return this;
    }
``` 

Да, обаче `userEntity.getAge()` връща Integer, който се оказва  null. Компилаторът ще е създал код, който прави auto unboxing и ще опита да превърне null в int, което завършва с `NullPointerException`. Оттам разбира се, не би могъл да работи и login-a. 

Поздрави,
Л.

**Comment by pako8101** [comment]
Благодаря за бързия отговор, промених всички на int но пак не сработва
както трябва :(,
като се регистрирам директно се логва, като логаутна не иска да се логне, в
базата съществува текущия юзър, и профайл
не работи..... странно

**Comment by luchob** [comment]
Последната промяна в репото изглежда от преди 2 седмици. Възможно ли е да го push-неш за да разгледам какво си променил и какво може да не е наред?

**Comment by pako8101** [comment]
Да добре, благодаря много, няма към кого другиго да се обърна :)

**Comment by luchob** [comment]
Привет! 

Две неща:

1) `ApplicationUserDetailsService` е анотиран с `@Component` и същевременно го декларираш с `@Bean` което означава, че в ApplicationContext-a имаш 2 юзър сървиса. Т.е. няма да работи.
2) `@EnableWebSecurity` не е необходимо.

И напомняне:

1) Съществуващите ти юзъри с age null няма да могат да се логнат
2) Логваш се с username, а не с email. Предполагам е направено така с умисъл :-)

Поздрави,
Л.

**Comment by pako8101** [comment]
Благодаря много, златен си, за пореден път доказваш че си най-добрия, почти
се оправиха нещата, вече се
логва но дава грешка на 'age'  като го задам го нулира и на profile ме
разлогва ......

**Comment by luchob** [comment]
Eee, това с age-a би трябвало да можеш да го дебъгнеш ;-) При регистраця мапваш user-a:

```
 UserEnt userEntity = new UserEnt().
                setFullName(userSubscribeBindingModel.getFullName()).
                setUsername(userSubscribeBindingModel.getUsername()).
                setEmail(userSubscribeBindingModel.getEmail()).
                setPassword(passwordEncoder.encode(userSubscribeBindingModel.getPassword()));
```

Обаче нямаш `setAge`, например нещо такова:

```
                setAge(userSubscribeBindingModel.getAge()).
```

Относно другото - не те разлогва, хвърляш ексепшън като отваряш профила:

``` 
org.springframework.security.core.userdetails.UsernameNotFoundException: User with username: null was not found!
	at HistoryAppGradleSecurity.session.LoggedUser.lambda$get$1(LoggedUser.java:84) ~[main/:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
	at HistoryAppGradleSecurity.session.LoggedUser.get(LoggedUser.java:84) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
``` 

Това идва от `LoggedUser`, който е някакъв остатък от първоначалната имплементация без spring security където ползвахме кръпка - session bean. Това трябва да изчезне.

Поздрави,
Л.

**Comment by pako8101** [comment]
Благодаря ще направя промените, ако има още нещо по нататък ще питам, че
няма към кого другиго да се обърна,
Благодаря много още веднъж,
Жив и здрав :)

**Comment by pako8101** [comment]
Привет,
да те помоля за малко помощ,при добавяне на article ми дава грешка, когато
е удобно да го погледнеш
https://github.com/pako8101/HistoryAppNewSpring2024

Благодаря много,
успешен ден :)

**Comment by luchob** [comment]
Здравей!

Не е болка за умиране този проблем :-) Но трябва да се опиташ да го разбереш. В момента положението е следното. Имаш един такъв код:

```
    @Override
    public void addNewArticle(ArticleServiceModel articleServiceModel) {
        Article article = modelMapper.map(articleServiceModel,Article.class);

        //article.setAuthor(userService.findCurrentUserLoginEntity());

//        article.setCategories(articleServiceModel.getCategories()
//                .stream()
//                .map(categoryService::findCategoryByName)
//                .collect(Collectors.toSet()));

        articleRepository.save(article);
    }

``` 

Модел мапъра успява да мапне категориите към празни ентита от тип Category. Което само по себе си е грешно. `article`-ът, който искаш да записваш съдържа set с N category entities които ги няма в ДБ, защото model mapper-a се е развихрил :-) . Поглед към ентитито. Връзката е ManyToMany:

``` 
    @ManyToMany
    private Set<Category>categories;//<-тук модъл мапъра е сложил няколко празни категории
``` 

Има едно пропърти cascade на `ManyToMany` което казва на hibernate какво да прави с тези ентитита при запис. По подразбиране е - нищо. Затова хибернейт се опитва да запише артикъла, вижда че има N несъществуващи категории в ДБ и понеже си му казал, че не трябва да прави нищо развява бял флаг:

```
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: HistoryAppGradleSecurity.model.entity.Category
``` 

В превод - виждам 2 категории които не са записани в ДБ, запиши ги в базата преди да запишеш артикула защото съм инструктиран да не ги записвам автоматично и не знам какво да направя. Ако беше така:

``` 
    @ManyToMany(cascade = CascadeType.ALL)
    private Set<Category>categories;
```

Щеше да се пробва да ги запише, което също не ти върши работа защото искаш да е много към много връзката.

Затова правилно си се досетил, но си коментирал кода:

```
//        article.setCategories(articleServiceModel.getCategories()
//                .stream()
//                .map(categoryService::findCategoryByName)
//                .collect(Collectors.toSet()));
``` 

С това разкоментирано - работи. Просто трябва да му сетнеш категории, които ВЕЧЕ се намират в ДБ.

Поздрави,
Л.

**Comment by pako8101** [comment]
Благодаря ти много, златен си
 Лек ден и до скоро ;)

**Comment by pako8101** [comment]
Привет Лъчо, когато ти е удобно да те помоля да погледнеш къде греша при
тестването,че някой от тестовете не палят въобще и грешките са странни.

Благодаря :)

**Comment by luchob** [comment]
Здравей!

Може да започнеш с най-елементарния тест, именно `HistoryAppNewApplicationTests`:

``` 
@SpringBootTest
class HistoryAppNewApplicationTests {

	@Test
	void contextLoads() {
	}

}
```

Той ще мине, само ако тестовия контекст се вдигне успешно. Но при теб не може да се случи, защото пакетите ти са именувани по различен начин в `main` и `test` модулите. Например `HistoryAppGradleSecurityApplication` е в пакет `HistoryAppGradleSecurity` а `HistoryAppNewApplicationTests`. Именувай всичко по консистентен начин, смени и имената на пакетите така че да не съдържат или започват с главна буква.

Поздрави,
Л.

**Comment by pako8101** [comment]
Оки действам, благодаря :)

**Comment by pako8101** [comment]
Здравей Лъчо,
с тестовете не се случват нещата не ми дава rename на основната папка и пак
не минават,
но нещо омазах user subscribe и не дава регистрация хвърля грешка и не мога
да открия от къде идва проблема.... тъкмо викам на финала съм и нещо се
омаже :(, когато ти е удобно да погледнеш.

Благодаря много

**Comment by luchob** [comment]
Здравей! 

Чета "не ми дава rename на основната папка и пак не минават" :-) 

Тестовете няма да минат със сигурност, докато не направиш пакетите да бъдат с еднакви имена. Ако искаш започни оттам, после направи push в github и отвори едно конкретно issue с описание, например: "Тестът Х не минава".

Иначе това issue става безкрайно и във всеки пост има по няколко проблема, които нямат точно описание. Ще очаквам включване :-)

Поздрави,
Л.
