### ISSUE TITLE
Как да изкараме съобщение в логин формата, че комбинацията от username и парола не съвпадат

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#50]
Привет, Лъчо,

забелязах, че в Mobileto не сме оправили напълно логин формата след вкарването на security.
Не ми е ясно и в моя проект как да го направя, тъй като преди за изкарването на съобщение, че усернейм и пасуорд не съвпадат правехме проверка по ДТО-то, което вече не ползваме. 
Това написах в контролера, но без DTO няма как да проверя параметрите:

![image](https://github.com/user-attachments/assets/4321d813-90b5-44ff-8890-25eeb718eaca)

**Comment by luchob** [comment]
Добро утро :-)

Ще кажа кой е най-елементарния вариант.

Според мен, трябва да започнем от разбирането на разликата между `failureForwardUrl` и `failureUrl`. Помъчих се да я обясня в [issue#6](https://github.com/luchob/softuni-spring-may-2024/issues/6). В login страницата не е необходимо да работим с DTO, достатъчен е един параметър за `username` тъй като никога не бива да препопулираме паролата на юзъра. Оттам нататък, ако се спрем на `failureForwardUrl` може да направим следния POST mapping:

```
    @PostMapping("/users/login-error")
    public String viewLoginError(@RequestParam("username") String userName,
        Model model){
        model.addAttribute("username", userName);
        model.addAttribute("showErrorMessage", true);

        return "login";
    }
```

`username` ще се предаде, тъй като това е serverside redirect както съм посочил в линка по-горе.

Поздрави,
Л.
