### ISSUE TITLE
Проблем с визуализацията на pdf 

### ISSUE THREAD

**Issue by VValMihova** [luchob/softuni-spring-may-2024#51]
***Връзка към проекта:***
[https://github.com/VValMihova/Invoice-app](url)

***Кратко описание:***
Здравейте, имам 2 основни проблема, абстрахирайки се от това, че проекта не е довършен 🤣  :
1. Когато изтегля pdf файл с фактурата си визуализацията ми не се показва, т.е. всичко се показва едно под друго без стилизация;
2. Не мога да "подкарам" да ми прави pdf файловете с UTF-8.

Опитах решения от интернет, но някак си не проработиха, не правя нещо както трябва, но не знам кое точно.

***Стъпки за репродуциране:***
След като пуснете проекта можете да се логнете с:
имейл: test@abv.bg
парола: 11111

1. В навбара ще видите "Моите фактури", там имам бутон за изтегляне на предварително създадена фактура. 
Тук използвам: 
В папката web - InvoicesController -  метода е downloadPdf, който води към PdfGenerationService, който от своя страна използва invoice-pdf.html за темплейт;

2. Също в навбара - "Създай отчет", с въвеждане на 21.07.2024 за начална и крайна дата показва отчет с продадените продукти от въпросния вече създаден инвойс. Там също има бутон за изтегляне:
В папката web - ReportController-  метода е downloadPdfReport, който води към PdfGenerationService, който от своя страна използва report-pdf.html за темплейт;

Виждам, че в htmlContent всичко се зарежда правилно, но след това нещата бъгват.

**Comment by luchob** [comment]
Здравей! :-)

Поздравления за смелостта да генерираш PDF ;-) Всеки, който е тръгнал по този път и иска да ползва свободен софтуер опира в flying saucer. И ние го ползваме и като цяло имаме доста неприятности именно с CSS-a. flying saucer използва доста стара версия на CSS (ако не се лъжа 2.1, която е на 12 години :-) ) и там съм почти сигурен, че няма flex. Съветът ми е да го направиш с най-елементарните и стари неща, тъй като по-новите feature-и в CSS няма да работят. Но ще е играчка, много сме се мъчили с точно такива форматирания. Мога само да ти стискам палци :-)

Относно втория проблем... мисля, че трябваше да се инсталира някакъв шрифт на рендерера, но не помня как точно ставаше това. Оставам бъга отворен и като ми остане време ще си поиграя. Дано остане де :-)

Поздрави,
Л.

**Comment by VValMihova** [comment]
Благодаря за бързия отговор :)! 
Ще се насоча към максимално простичък шаблон за инвойса. 
Относно шрифта и аз прочетох такива коментари и съм сложила един шрифт в ресурсите, но не постигнах успех...

**Comment by luchob** [comment]
Всъщност, подкарах го с verdana. Ето какво трябва направих. Първо увери се, че енкодинга на properties файловете ти в IntelliJ e UTF-8 (защото по подразбиране е ISO8859-1). Това става в менюто с настройките:

<img width="962" alt="Screenshot 2024-07-21 at 15 19 51" src="https://github.com/user-attachments/assets/f3b1526b-2b17-4b78-a61d-e996aa700233">

После, аз лично свалих от някъде Verdana.ttf и я сложих на компютъра си. Добавям абсолютния път към позицията на фонта:
```
      renderer.getFontResolver()
          .addFont("/Users/XXX/absolute/path/Verdana.ttf",
              BaseFont.IDENTITY_H,
              BaseFont.NOT_EMBEDDED
          );
```

В PDF service-a слагам и текущия локал с помощта на `LocaleContextHolder`, например:

```
    Context context = new Context();
    context.setLocale(LocaleContextHolder.getLocale());
    context.setVariable("reportData", reportData);
```

След това бях променил и html-a малко, ето в тези редове:
```
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
         * { font-family: Verdana, sans-serif; }
  </style>
  <title th:text="#{report.title}">Sales Report</title>
  <style>
      body {
          margin: 0;
          padding: 20px;
      }
``` 

<img width="815" alt="Screenshot 2024-07-21 at 16 11 26" src="https://github.com/user-attachments/assets/86f386a7-4bac-40ae-b766-42abfbf13437">

Поздрави, 
Л.

**Comment by luchob** [comment]
Ех, изпревари ме с 1 минута :-)

**Comment by VValMihova** [comment]
Леле, уникално, **много благодаря**!!! 
Отивам да го пробвам! 
Хубава неделя :)
