### ISSUE TITLE
Проблем с IntegrationTests

### ISSUE THREAD

**Issue by BlagoyVelinov** [luchob/softuni-spring-may-2024#52]
Здравей, Лъчо

Имам проблем с IntegrationTests  в REST-api което изнесох подобно на това което направи с мобилето.
https://github.com/4ukNoris/Spring-Project-REST-API.git

Проблемът е: тестовете ни тръгват изобщо и не знам какво се случва, в интернет не успях да намеря адекватна помощ.

Пускам ти Pastebin: https://pastebin.com/T8NYehYj   

Това е стактрейса на това което се случва когато пусна който и да било тест.
Подобен на този проблем имам и в основния проект с IT.

**Comment by luchob** [comment]
Здравей!

Изобщо не знам защо, но в тестовото `application.yaml` имаш
```
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
``` 

В превод може да звучи като: "изключи базата с данни, и всички репозиторита".

Откъдето:

```
Parameter 0 of constructor in bg.softuni.CinemaTickets_Movies.services.impl.BookingTimeServiceImpl required a bean of type 'bg.softuni.CinemaTickets_Movies.repositories.BookingTimeRepository' that could not be found.
```
Махни тези странни редове.

Поздрави,
Л.

**Comment by BlagoyVelinov** [comment]
Благодаря. След като го махнах отново не минават тестовете но поне се смени
ексепшъна. Ще пробвам да открия проблема.

На пн, 22.07.2024 г., 13:08 ч. Lachezar Balev ***@***.***>
написа:
