### ISSUE TITLE
Проблем с Integration tests

### ISSUE THREAD

**Issue by SavinaDzhenimova** [luchob/softuni-spring-may-2024#53]
Линк към github проекта: https://github.com/SavinaDzhenimova/HomeDeliveryApp

Здравей! Днес започнах да пиша integration tests към проекта ми, но имам проблем с конфигурацията и тестовете не тръгват. Гледах отново лекцията и следвам стъпка по стъпка, но явно пропускам нещо. Мисля, че съм добавила всички необходими dependencies, от yaml файла съм махнала само частта с datasource, за да не се свързвам с истинската база, но при пускане на contextLoads() получавам следната грешка:

java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@5d3b0f8a testClass = com.homedelivery.HomeDeliveryApplicationTests, locations = [], classes = [com.homedelivery.HomeDeliveryApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@b9b00e0, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@53aac487, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2e6a8155, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@46cdf8bd, org.springframework.boot.test.context.SpringBootTestAnnotation@ac400eff], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]

Благодаря предварително за помощта!

**Comment by luchob** [comment]
Здрасти!

Първото нещо, което е проблем е този ред в тестовото application.yaml:

```
        dialect: org.hibernate.dialect.MySQL8Dialect
``` 

Все едно казваш говори на h2 все едно е MySQL. Но то не е. И оттам идва и втория ти проблем, който е идентичен с този на колегата [тук](https://github.com/luchob/softuni-spring-may-2024/issues/36).

Него може да решиш като:

* настроиш H2 в MySQL compatible mode или........
* testcontainers ;-)

За последното ще дам пример в докер лекцията, надявам се. Но е доста сложно и ти препоръчвам да пробваш с първите опции. Възможно е и да "столкнеш" малко какво е направил колегата :-)

Поздрави,
Л.
