### ISSUE TITLE
 Въпрос относно JwtService  и генерирането на токън

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#54]
*Връзка към проекта:*
https://github.com/baldzhiyski/Crossfit-Web-App

Здравейте , имам въпрос отностно генерирането на токена , което започнахме да правим миналия път. В моя проект смених малко логиката и сега вместо да викам чрез Rest Client моите евенти от Rest API - то , ги викам директно чрез js , тъй като исках да сменя логика за pagination . За да мога все пак да дърпам нещата от там трябваше да сложа една анотация в  REST API то CrossOrigin . Мисля , че сега обаче този токън няма да работи , тъй като не използвам самия Rest Client.  Предполагам обаче за post Mapping би трябвало да сработва , тъй като там вече го използвам .

Също  дебъгнах и в момента този интерсептор не се хваща въобще , но предполагам това е така , защото ги викам през js. В този случай има ли все пак начин да използвам логиката за този токън и за тaзи get заявка , която правя ? Js Файла се казва pagination.

**Comment by luchob** [comment]
Здрасти!

Доколкото разбирам, проблемът е следния.

**Преди:** Заявката е минавала от браузъра (син) през сървъра (зелен) до ивентите (жълт).
**Сега:** Заявката минава от браузъра (син) до ивентите (жълт).

<img width="911" alt="Screenshot 2024-07-24 at 18 24 42" src="https://github.com/user-attachments/assets/22fec4c5-9ddc-4d8d-984d-f5154bb18517">

**Проблем:** Комуникацията между съвъра (зелен) и ивентите (жълт) става посредством JWT authentication, което е пък недостъпно за браузъра (син). 

В практиката обикновено има и друг играч - identity provider (например такъв е KeyCloak). Та в такъв сетъп браузъра и user-a си вземат access token от IDP-то (през OAuth2/OIDC протокол), който е подписан с подписа на IDP-то и ползват този токън за комуникация с ивентите (жълтите). Те пък от своя страна верифицират сигнатурата с помощта на IDP-то. Този истински setup е прекалено сложен за да го реализираме на курса, затова направихме този супер опростен вариант.

Сега не ти остава друго освен:

* да върнеш назад и комуникацията да минава както преди.
* да го хакнеш още малко и JS-a (син) да си взема по рест JWT токен за логнатия юзър от сървъра (зелен) и след това да го праща на ивентите в хедърите на заявката (жълт)

Последното ще работи, но в практиката едва ли ще срещнеш подобен setup.

Поздрави,
Л.
