### ISSUE TITLE
Spring and React connection (mani Issue Spring Security)

### ISSUE THREAD

**Issue by Viktor-U** [luchob/softuni-spring-may-2024#55]
https://github.com/Viktor-U/HealthHeaven

Идеята ми е да свържа Spring с React и спринга да ми е рест апи, но post заявката ми за регистрация не работи тествах я с postman и разбрах, че като махна Spring security работи. Мисля, че проблема ми е в конфигурацията и ще съм много благодарен да ми обясните къде бъркам и как мога да го оправя.(Търсих информация на всякъде, също ще бъда благодарен дори само да ми покажете сайт от който мога да изчета как стават нещата.)

Стъпки за репродуциране:

Мисля, че с рефакториране на файловете в папката 'config' биха се оправили нещата, но не знам как точно ще стане това.

Извинете за неподредения код, но 4-дена се мъча само над проблема с връзката.Направил съм и една get заявка която работи просто за да тествам връзката(взима всички users от базата данни и ги изписва на екрана).

**Comment by luchob** [comment]
Здравей!

Въпреки, че не съм ползвал React до момента, съм 99% сигурен че става въпрос за CSRF защитата, която имплементира spring security. Накратко - при POST, DELETE, PATCH (но не и GET) заявки се праща CSRF токън, като интеграцията е почни невидима когато работиш с thymeleaf. Това обаче няма да е така с react. 

Едно от предложенията ми е да погледнеш CookieCsrfTokenRepository, което би могло да ти свърши работа. Повече детайли -> https://stackoverflow.com/questions/62648098/what-does-cookie-csrftokenrepository-withhttponlyfalse-do-and-when-to-use-it

Поздрави,
Л.

**Comment by Viktor-U** [comment]
Благодаря за помоща.
