### ISSUE TITLE
Въпрос относно coverage

### ISSUE THREAD

**Issue by SavinaDzhenimova** [luchob/softuni-spring-may-2024#56]
Линк към проекта ми в github: https://github.com/SavinaDzhenimova/HomeDeliveryApp

Здравей! Довърших unit и integration тестовете към проекта си като покрих 60% от кода както е и в изискванията за финалния проект. Иска ми се обаче да увелича coverage-а с още няколко процента, но вече съм изтествала почти всичките си контролери и сървиси и не виждам как това да се случи. Това на структурата на проекта ми ли се дължи или пък на това, че имам доста unit тестове? Ако заменя част от тях с integration тестовете дали coverage-а ще се повиши?

**Comment by luchob** [comment]
Здравей, пускайки тестовете ти с coverage през IntelliJ виждам 84% coverage което е далеч над изискванията. Така че не виждам нищо притеснително. Или бъркам?

<img width="845" alt="Screenshot 2024-07-24 at 18 40 01" src="https://github.com/user-attachments/assets/90d327c1-7875-4e76-9f18-cf83a564dbc9">


Поздрави,
Л.

**Comment by SavinaDzhenimova** [comment]
Пуснах ги отново и при мен също излизат 84%. Явно не съм пуснала тестовете на директорията com.homedelivery, а на service или web. Много благодаря.
