### ISSUE TITLE
failureForwardUrl VS failureUrl(Spring Security)

### ISSUE THREAD

**Issue by Aleksandra-Ilieva** [luchob/softuni-spring-may-2024#6]
Здравейте, може ли кратко обяснение за разликата между failureForwardUrl и failureUrl(Spring Security), понеже се опитвах да
покажа съобщение, когато потребителят се логне, но въведе грешно потребителско име или парола. Аз бях използвала failureForwardUrl  и нищо не се показваше, след доста мъчене да разбера от къде идва грешката, разбрах че трябва да е failureUrl и така се получи, но не  разбрах каква е разликата между двете и защо с failureForwardUrl не можеш да покажеш грешката. Благодаря предварително!

**Comment by luchob** [comment]
Здравей, Алекс!

Ще се опитам да го обясня. Както пише в [документацията](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/form.html), ако аутентикацията не успее то тогава се извиква един клас, който имплементира [AuthenticationFailureHandler](https://docs.spring.io/spring-security/site/docs/6.3.0/api/org/springframework/security/web/authentication/AuthenticationFailureHandler.html) и който поема нещата в свои ръце.  Когато използваш `failureForwardUrl` или `failureUrl` в конфигурациите си, това което се случва "отдолу" е че настройваш различни имплементации на `AuthenticationFailureHandler`. Ето, може да надникнем в кода на Spring:

```
public FormLoginConfigurer<H> failureForwardUrl(String forwardUrl) {
		failureHandler(new ForwardAuthenticationFailureHandler(forwardUrl));
		return this;
	}
```

``` 
public final T failureUrl(String authenticationFailureUrl) {
		T result = failureHandler(new SimpleUrlAuthenticationFailureHandler(authenticationFailureUrl));
		this.failureUrl = authenticationFailureUrl;
		return result;
	}
```
Нека видим какво прави всяка от тях.

1. `SimpleUrlAuthenticationFailureHandler` (или `failureUrl`). Тази имплементация прави **browser redirect** както е показано на схемата отдолу.

<img width="898" alt="Screenshot 2024-06-12 at 8 14 01" src="https://github.com/luchob/softuni-spring-may-2024/assets/10339738/53baa7e5-5ad7-42b6-87e3-95ad800524e8">

Виждаш, че това е типичния `POST/redirect/GET` сценарий. Забележи обаче, че последната заявка към `login-error` e GET. Т.е. при този сценарий ако искаш да бъде обработена се изисква `@GetMapping("/login-error")`. Моделът се запазва.

2. `ForwardAuthenticationFailureHandler`  (или `failureForwardUrl`). Тази имплементация прави **server redirect** както е показано на схемата отдолу.

<img width="879" alt="Screenshot 2024-06-12 at 8 20 09" src="https://github.com/luchob/softuni-spring-may-2024/assets/10339738/642a4385-b78e-4d49-aa18-aa81dd747dd4">

Заявката е само една, а редиректът се случва на сървъра без знанието на клиента (браузърът). Т.е. при този сценарий ако искаш да бъде обработена се изисква  `@PostMapping("/login-error")`. Моделът се запазва.

Надявам се това ще ти помогне да разбереш как работят двете и оттам ще се досетиш защо не ти се е получило в единия случай. :-)

Поздрави,
Л.

**Comment by Aleksandra-Ilieva** [comment]
Благодаря много за отговора, мисля че разбирам, аз конкретно показвах грешката чрез параметър ето така:
.failureUrl("/login?error=true").permitAll().
Контролер:
 @GetMapping("/login")
    public String login(@RequestParam(name = "error", required = false) String error, Model model) {
        if (error != null) {
            model.addAttribute("error", "Invalid username and password.");
        }
        return "login";
    }
Темплейт:
 <div th:if="${param.error}" class="text-danger">
                    Invalid username and password.
  </div>
Обобщение:
Тоест ако исках да използвам failureForwardUrl трябваше да имплеметирам директно PostMapping, защото се изпраща същата post заявка. Тоест нещо такова:
@PostMapping("/login")
public String loginPost(HttpServletRequest request, Model model) {
    Exception exception = (Exception) request.getAttribute(WebAttributes.AUTHENTICATION_EXCEPTION);
    if (exception != null) {
        model.addAttribute("error", "Invalid username and password.");
    }
    return "login";
}
Правилно ли съм разбрала?
Поздрави,
Александра

**Comment by luchob** [comment]
Да, трябваше да е `@PostMapping`. Относно Exception-a  в примера ти, това прави `ForwardAuthenticationFailureHandler`-a:
```
public class ForwardAuthenticationFailureHandler implements AuthenticationFailureHandler {

	@Override
	public void onAuthenticationFailure(HttpServletRequest request, HttpServletResponse response,
			AuthenticationException exception) throws IOException, ServletException {
		request.setAttribute(WebAttributes.AUTHENTICATION_EXCEPTION, exception);
		request.getRequestDispatcher(this.forwardUrl).forward(request, response);//<--server redirect
	}
}
```

Възможно е да използваш и нещо далеч по просто при сървър редирект, например:

``` 
    @PostMapping("/login-error")
    public String onFailedLogin(Model model) {} 
```

Това ще се вика с попълнен модел и то само при неуспешен логин. В модела би трябвало да е и user name-a.

Поздрави,
Л.

**Comment by Aleksandra-Ilieva** [comment]
Благодаря много, да аз използвам първия вариант с failureUrl струва ми се по-лесен.
