### ISSUE TITLE
Проблем при запазване на LocalDateTime в базата

### ISSUE THREAD

**Issue by mario9502** [luchob/softuni-spring-may-2024#60]
https://github.com/mario9502/RegalCinema/tree/master

Здравей, Лъчо
проблемът е следния, когато запаметявам в базата обект съдържащ в себе си LocalDateTime със съответната дата и час, запазените данни се различни от това, което съм подал като стойност на конкретни полета. Пример: подадена стойност 15-08-2024 14:00, стойност запазена в базата данни 15-08-2024 11:00 (т.е. винаги запазва часа с 3 часа назад от подадената стойност).
Проверявам в дебъг и в IDE-то стойностите са си акуратни, но при запазването връща с 3 часа...
Прерових гугъла, пробвах да задам часова зона на DateTimeFormatter-а, пробвах да задам часова зона на базата директно от Workbench, пробвах да задам часова зона от application.yaml файла като накрая на url-a задам "serverTimezone=UTC+3" ескейпвайки плюса, за да не гърми. Резултат никакъв 

*Стъпки за репродуциране:*

С postman изпращаш POST заявка на следния адрес: http://localhost:8080/marathons/add  с body 

{
    "name": "2024 Summer Mega Marathon",
    "location": "Ski Pista Bansko",
    "start": "25-07-2024 14:00",
    "end": "10-08-2024 23:00",
    "movies": [ "Harry Potter", "Dune: Part One", "Home Alone"],
    "description": "descriptiondescription"
}

**Comment by luchob** [comment]
Здравей!

UTC или т.нар. универсално време през лятото отстои на 3 часа от нашето, българско време. През зимата разликата е 2 часа. В `application.yaml` имаш зададено `serverTimezone=UTC` което е синоним на `connectionTimeZone=UTC`. Това определя тайм зоната на сесията между JVM-a и MySQL, която пък от своя страна определя как да бъде превърнато времето което изпращаш към MySQL преди записа му в базата. Подробности [тук](https://dev.mysql.com/doc/connector-j/en/connector-j-time-instants.html). Ако искаш да не ги записва като UTC сложи стойност LOCAL както е посочено в документацията или въобще разкарай пропъртито от connection string-a.

Поздрави,
Л.

**Comment by mario9502** [comment]
Супер, много благодаря!
