### ISSUE TITLE
Проблем при записване за appointment  с register бутона в details.html

### ISSUE THREAD

**Issue by DzhansuDikmemehmed** [luchob/softuni-spring-may-2024#61]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*

[_Поставете [връзка](https://github.com/) към проекта си по подобен начин._](https://github.com/DzhansuDikmemehmed/MyProjectSoftuni)

*Кратко описание:*

Възможно най-накратко опишете:

1. Какво очаквате да се случи
2.Искам след като натисна бутона register  в details.html клиента да се запише и полето remainingPlots да намалее, като клиент може да се записва и отписва, докато статусът е активен и не преминава максималните участници
3. Какво всъщност се случва
4. Това се случва, когато не съм логната, но след като се логна ми изписва 403,2:166 Error: TypeError: Failed to execute 'fetch' on 'Window': Invalid name
    at HTMLButtonElement.<anonymous> (2:150:13)
5. (Желателно) Какво опитахте
Проверих дали мета таговете за CSRF се заеждат правилно, но не се зареждаха. проверих и SecurityConfig мисля, че пътищата са правилни
*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които бързо може да се репродуцира проблемът.

**Comment by luchob** [comment]
Добър ден! :-)

Първото нещо което ми направи впечатление, когато разгледах проекта е че мапинга ти е грешен:
```
    @PostMapping("/register/{id}")
    public ResponseEntity<?> registerForAppointment(@PathVariable("id") Long id){
```

Допускам, искала си да е така:
```
    @PostMapping("/appointments/register/{id}")
```

Както и да е, това не е основния проблем. Това, че нещо се случва когато не си логната е измамно. Нищо не се случва реално. Защо? Защото, когато не си логната отговорът от fetch заявката е всъщност 302 редирект към логин страницата който се "глътва" от js-a, и уж се намалят Remaining Spots, но на съвръва са си едни и същи.

Когато се логнеш обаче, нещата стават по различни и заявката гръмва с 403 вместо да върне 302. Това обаче не се "глътва" и ти го виждаш. Защо 403 обаче? 403 идва заради CSRF защитата. Както говорихме на лекциите, когато
печатиш с thymeleaf обикновена форма става малка "магия" и всъщност крайната HTML-a форма изглежда например така:
```
<form method="post" action="users/logout">

      <input type="hidden" name="_csrf" value="cKBBj_t35-vyZoQ4mZSZhaXuFZdrltbOIZ9_w6sXHT36x7LeE5d2uZ5O0d_fBLcIrLmtspzaOK4I9OXjRftJ95h0KV6ZooS6"/>
      <button type="submit">Logout</button>

</form>
```

Обаче сега при fetch такова нещо не се случва и съответно _csrf не заминава в заявката и Spring Security ти казва -> 403 js-a гръмва и виждаш онази грешка.

В едно упражнение преди време направихме така. Сложихме _csrf информацията [в meta таг](https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/templates/fragments/commons.html#L6). След това я [прочетохме](https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/static/js/comments.js#L3-L4) и [изпратихме](https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/static/js/comments.js#L62) в POST заявката.

Друг вариант е да направиш Register на submit button във форма и да не се занимаваш с JS изобщо. Изборът е твой. :-)

Поздрави,
Л.
