### ISSUE TITLE
Проблем при изтриване

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#62]
Здрасти, Лъчо,

имам проблем с изтриване на рецепта, когато вече някой я е лайкнал, тъй като прави релация с юзър таблицата.
Проблема е в home страницата, при изтриване на рецепта добавена от мен.
Опитах с @Transactional, но не работи, може ли да помогнеш как да реша проблема?

Това е грешката: 
Cannot delete or update a parent row: a foreign key constraint fails (`delicious_recipes`.`users_liked_recipes`, CONSTRAINT `FK2x4dw0riyuew05m56simvyhj0` FOREIGN KEY (`liked_recipes_id`) REFERENCES `recipes` (`id`))

https://github.com/BogoevaPetya/DeliciousRecipes

Поздрави,
Петя

**Comment by BogoevaPetya** [comment]
И още един въпрос. Опитвам се да заменя този код 
![image](https://github.com/user-attachments/assets/95a67c79-c96a-43d1-b856-f59210c1f75b)

с това, но винаги ми връща false

user.getFavoriteRecipes().contains(recipe);

Каква е причината?

**Comment by luchob** [comment]
Здравей!

Анотацията `@Transactional` не може да ти разреши проблемът по никакъв начин, тъй като тя очертава границата на транзакцията към базата, а твоят проблем е чупенето на foreign key. Т.е. в users_favorite_recipes имаш ред, който сочи рецептата и ако базата изтрие рецептата този ред ще сочи към несъществуваща рецепта. Базата не позволява това и това е смисъла на foreign ключа. 

Вариантите са най-различни и този който бих ти препоръчал е да изкараш харесваните рецепти като отделно ентити, например:

```
@Entity
@Table(name = "user_liked_recipe")
public class UserLikedRecipe extends BaseEntity{

  @ManyToOne(fetch = FetchType.LAZY)
  private UserEntity user;

  @ManyToOne(fetch = FetchType.LAZY)
  private Recipe recipe;

  public UserEntity getUser() {
    return user;
  }

  public UserLikedRecipe setUser(UserEntity user) {
    this.user = user;
    return this;
  }

  public Recipe getRecipe() {
    return recipe;
  }

  public UserLikedRecipe setRecipe(Recipe recipe) {
    this.recipe = recipe;
    return this;
  }
}
``` 

Тогава може да имаш и репозитори:

```
@Repository
public interface UserLikedRecipeRepository extends JpaRepository<UserLikedRecipe, Long> {
  @Transactional
  void deleteByRecipe(Recipe recipe);
}
``` 

Ето как работи:

```
    UserEntity user = new UserEntity();
    user.setUsername("user");
    user.setEmail("test@example.com");
    user.setPassword("123456");

    user = userRepository.save(user);

    Recipe recipe = new Recipe();
    recipe.setName("Recipe");
    recipe.setIngredients("Ingredients");
    recipe.setInstructions("Instructions");
    recipe.setTimeForCooking(10);
    recipe.setAddedBy(user);
    recipe.setCategory(categoryRepository.findByName(CategoryName.DESSERT).orElseThrow());

    recipeRepository.save(recipe);

    UserLikedRecipe userLikedRecipe = new UserLikedRecipe();
    userLikedRecipe.setUser(user);
    userLikedRecipe.setRecipe(recipe);

    userLikedRecipeRepository.save(userLikedRecipe);

    userLikedRecipeRepository.deleteByRecipe(recipe);
    recipeRepository.delete(recipe);
```

Относно втория ти въпрос - каква е причината. 

Причината е че `contains` метода на колекциите в Java зависи от имплементацията на методите `equals` и `hashCode` на обектите, които се намират вътре в колекцията. При теб такава имплементация няма, което означава че се ползва тази на java.lang.Object или по-просто казано - сравняваш ги по reference. Все едно object1 == object2. В случая референциите са различни и затова винаги получаваш false. Създаването на `equals` и `hashCode` в entities не е толкова просто и ако разтърсиш малко ще намериш много чудесни статии по въпроса :-)

Последно - в user entity-то ти имаш прекалено много eager релации които водят до join с прекалено много таблици когато искаш просто да вземеш един user.

Поздрави,
Л.

**Comment by BogoevaPetya** [comment]
Здравей отново, @luchob

истината е, че супер много се обърках. Създадох ново ентити, както ме посъветва, но в това ново repository - UserLikedRecipeRepository как да потърся дали този юзър вече не е харесал конкретната рецепта, така че да може само веднъж да я хареса? Би ли погледнал какво съм направила и дали има смисъл, защото много забих:
https://github.com/BogoevaPetya/DeliciousRecipes

Поздрави,
Петя

**Comment by luchob** [comment]
Здравей, @BogoevaPetya!

Мисля, че не е толкова страшно или пък объркващо :-) Възможно е, например, да добавиш следния метод:

```
@Repository
public interface UserLikedRecipeRepository extends JpaRepository<UserLikedRecipe, Long> {
    boolean existsByUserUsernameAndRecipeId(String username, Long recipeId);
}
```
Това резултира в следното куери от Hibernate:

``` 
select
        ulr1_0.id 
    from
        user_liked_recipe ulr1_0 
    left join
        users u1_0 
            on u1_0.id=ulr1_0.user_id 
    where
        u1_0.username=? 
        and ulr1_0.recipe_id=? 
    limit
        1
``` 

Поздрави,
Л.
