### ISSUE TITLE
Проблем при запазване на ентити в базата данни

### ISSUE THREAD

**Issue by tony9701** [luchob/softuni-spring-may-2024#63]
*Връзка към проекта:*

https://github.com/tony9701/propertiesApp

*Кратко описание:*

1. Какво очаквате да се случи

при добавяне на имот в сайта би трябвало сървиса да създраде "propertyPhoto" entity от предоставената информация от клиента (така и става), понеже имат връзка първо създавам имота без снимка "property", след това създавам снимката с релация към имота "propertyPhoto" и след това се опитвам да добавя вече създадената снимка към "property" ентитито.

3. Какво всъщност се случва

 гърми с UnsupportedOperationException

става въпрос за метода addProperty в сървиса PropertyServiceImpl

**Comment by tony9701** [comment]
проблема е решен. Оказа се, че проблема беше в часта с "List.of()" не съм видял, че това връща Immutable Collection и от там гърми. Поправих го като просто създадох нов арей лист и там си добавих снимката и чак след това сетнах новия арей лист към Property :)

**Comment by luchob** [comment]
Здрасти!

Точно щях да ти кажа да си направиш един метод:

```
    public void addPropertyPhoto(PropertyPhoto photo) {
        this.propertyPhotos.add(photo);
    }
``` 

И като създаваш пропърти:

``` 
PropertyPhoto photo = propertyPhotoService.createPhoto(property, addPropertyDTO.getPhotoUrl());
        property.addPropertyPhoto(photo);
        propertyRepository.save(property);

``` 

Поздрави,
Л.

**Comment by tony9701** [comment]
Ех и за това не се сетих. Опита си казва думата, супер си! Поздрави!
