### ISSUE TITLE
Въпрос относно генериране на pdf

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#64]
Здравейте , имам към проекта страница , в която са всички тренировки за седмицата и искам да направя бутон , с който всеки user ще може да свали pdf файл  на самия график . Бихте ли ми дали съвет как би станало това най - лесно ? Помня , че бяхте споменали нещо за това , но не мога да се сетя библиотеката , която бяхте казали. 

Поздрави !

**Comment by luchob** [comment]
Здрасти!

Пошпионирай [тук](https://github.com/luchob/softuni-spring-may-2024/issues/51).

Поздрави,
Л.
