### ISSUE TITLE
Няма комуникация между restClien и rest сървър

### ISSUE THREAD

**Issue by roskonenov** [luchob/softuni-spring-may-2024#67]
name: "Няма комуникация между restClien и rest сървър"

title: 'Travel Nest'

labels: project-help

assignees: luchob

*Връзка към проекта:*

[TravelNest](https://github.com/roskonenov/TravelNest) това е линк към основното ми приложение

[TravelNestAccount](https://github.com/roskonenov/TravelNestAccount) а това към по - малкото спомагателно приложение

*Кратко описание:*

Идеята ми тук е когато се цъкне върху линка за "MyAccount" в нав-бара от главния апп да се редиректнем към по малкото приложение,

което ще има за цел единствено да менажира страницата с информация за акаунта на текущия потребител. Там чрез restClient ще се изтегли

необходимата информация от главния апп.

Само че не работи. Не мога да накарам restClienta  да се свърже с Rest сървъра на основния апп.

Като прави GET заявки към него не се получава нищо. Мисля че е нещо от настройките. 

При изпращане на заявка от браузъра се връща необходимата информация, при Postman се връща HTML темплейт, а комуникация между двете приложения изобщо няма.

Настройките са ми като вашите от лекциите, но нещо пропускам.

При стартиране на приложението db ще се попълни с няколко примерни юзъра и други ентити обекти.

Необходимите Ви environment variables са:

IMGUR_CLIENT_ID = 4106833c5570c61

USER_PASSWORD = Travelnest1@; - или както си я зададете вие, но трябва да отговаря на условия за

голяма и малка буква, число, специален знак и дължина от поне 8 символа :)

JWT_SECRET = TWH10gPdM6QVjiaWCqoaTWH10gPdM6QVjiaWCqoa - или каквото Вие си изберете

трите дефолтни юзъра са: 

georgi79,

elena_jelyazkova, 

roskonenov - това е админа

Просто стартирайте двете приложения и след като се логнете в осн. сайт натиснете в нав-бара върху потребителското си име или иконката с човече,

за да видите как не се случва нищо освен редирект.

**Comment by luchob** [comment]
Здравей! 

Малко е странен целия този сетъп. Всъщност има комуникация между сървисите, но не я забелязваш тъй като този ендпойнт:

``` 
@GetMapping("/get-user-favorites")
``` 
e секюрнат, и при това с cookie базирана аутентикация. Ако го разрешиш за всички ще видиш че ще го извика.  Обаче цялата работа е много странна и някак не ми се връзва..

<img width="688" alt="Screenshot 2024-07-28 at 12 42 03" src="https://github.com/user-attachments/assets/7c20b910-ab62-4945-8f7c-e672750adfb5">


Значи в главното приложение на 8080 се аутентицираме с form login и вече имаме session cookie.
Оттам се прехвърляме в съвсем друго приложение, където сме напълно анонимни, тъй като... е съвсем друго приложение, на друг порт и т.н. Т.е. губим цялата информация за логнатия юзър. Finito. 

След това TravelNestAccount извиква през REST нещо на 8080. И да - вика го, настройките на рест клиента са ОК, просто тъй като липсва аутентикация TravelNest те редиректва към логин страницата и затова рест клиента "глътва" грешката (той кърми при 4хх и 5хх грешки).  В `/get-user-favorites` няма информация за логнатия юзър и няма и как да има, тъй като кукито е загубено по пътя. Не виждам как това ще работи.

Ако нещо може да работи то е по-скоро TravelNest да вика TravelNestAccount през REST с JWT token а не обратното.

Поздрави,
Л.

**Comment by roskonenov** [comment]
Разбрах те напълно. Аз си мислих, че с първата гет завка TravelNest ще изпрати инфо за логнатия юзър и той ще си се логне автоматично и там, но явно не съм го доизмислил. Идеята ми беше да стане нещо по различно от обикновен сървис с база данни както го правихме в лекциите. Просто за да упражня Rest Api.

**Comment by roskonenov** [comment]
Здравей отново Лъчо, 
Благодаря ти за съветите от по рано.
Мисля че го измислих как да стане, като пратя jwt токен с инфо за юзъра през редирект урл-то. И всичко си върви добре и дори се логва текущия юзър в другия апп успешно, обаче в момента в който влезе в контролера и се редиректне към някакъв ендпоинт, се случва някаква черна магия и Spring като че ли забравя за този юзър. Моля те хвърли един поглед ако не ти преча, че съм на ръба на нервна криза вече.

**Comment by luchob** [comment]
Роска, цялата идея е странна и затова ти изглежда че Spring се държи странно :-) Това, което мога да направя в случая е да ти обясня защо наблюдаваш това поведение.

<img width="787" alt="Screenshot 2024-07-29 at 8 44 51" src="https://github.com/user-attachments/assets/f8db70e9-22a0-43bc-8a92-56c96d396868">

Цялото действие се развива в рамките на 2 заявки, както можеш да видиш в Network таба. Първата заявка е към redirect ендпойнта заедно с един token. Тя пристига на сървъра, JWT аутентикацията сработва и всичко е точно. Само че, тази заявка завършва с редирект и статус код 302.

```
    @GetMapping("/redirect")
    public String redirect(){
        return "redirect:/my-account";
    }
``` 

Този статус се прихваща от браузъра и обработва като се гледа Location header-a, който пък сочи към `my-account`. Следва втора, напълно анонимна заявка към `my-account`. В нея няма нито тоукън, нито cookie, нито каквото и да е идентифициращо юзъра който прави заявка. Оттам контролера се извиква с анонимен юзър.

Поздрави,
Л.

**Comment by roskonenov** [comment]
Ясно, благодаря ти! Ако не измисля нещо друго май ще се сменя концепцията. Но ми се искаше да е малко по различно, а не просто да повторя проекта от лекциите с изнесения сървис.

**Comment by luchob** [comment]
Приложенията, които се аутентикират с OIDC (напр. angular приложенията) обикновено пазят bearer token-a в session storage-а на браузъра и всичките изходящи с помощта на JS заявки се "сдобиват" с този тоукън в хедърите. Само че, механизмът с който се сдобиват с тоукъна е доста по-сложен от това което направихме, и там има трети играч - identity provider който раздава тоукъни. Горе долу става така:

1.  Client приложението редиректва user-a към IDP-то.
2. Там юзъра се аутентицира (например логин с google, facebook, keycloak и т.н.)
3. IDP-то връща юзъра към client приложението с един специален код
4. Клиентът разменя този специален код срещу bearer token
5. След това започва да комуникира със сървъра с bearer token и за разлика от нашия сценарий server-a верифицира сигнатурата на тоукъна с помощта на IDP-то.

Имай предвид, че това е още по-сложно, тъй като JWT тоукъните например имат expitation време, което обикновено е доста кратко. Стават невалидни и трябва да се рефрешват. 

При твоя вариант може да ти хрумна да пазиш JWT тоукъна в cookie, но това ще бъде единствения проект с такъв подход в света :-) ;-)  :-) 

Затова и направихме един съвсем простоватичък setup с два сървиса и споделен ключ, тъй като се съмнявам че пълният вариант щеше да може да се обясни по достъпен начин на всички. То и този като че ли е малко недостъпен, но поне се видя какво представлява един JWT bearer тоукън, надявам се.

Поздрави,
Л.

**Comment by roskonenov** [comment]
Интересно звучи да, ама ми стана ясно, че газя към дълбокото с моите джуниър плавници. Явно няма да стане още от първия проект :) За сега ще се придържам към видяното и наученото.  Благодаря за отделеното време.
