### ISSUE TITLE
Проблем с избора на места

### ISSUE THREAD

**Issue by BlagoyVelinov** [luchob/softuni-spring-may-2024#68]
Здравей, Лъчо
Оправих проблема с избора на местата но ми остана проблема с визуализирането на данните от ордера на последващата страница. Когато използвам th:each, не се показват данните дори и статичните данни на страницата в дадения скоуп на th:each-a изчезват.
Ако го сложа най от горе, цялата страница става бяла.

https://github.com/4ukNoris/Spring-Project.git

Още не съм качил последните промени понеже ги довършвам и след това ще кача и тях.

Относно стартирането на проекта мисля че го оправих.

**Comment by BlagoyVelinov** [comment]
Готово всичко съм качил ако можеш когато имаш време да погледнеш confirm-order.html
Благодаря много и извинявай за тормоза!

**Comment by luchob** [comment]
Здравей!

Така и не разбрах откъде да си купя билет от сайта след като съм създал movie, но... Все пак вместо да се предам сложих фейк данни в ДВ, написах фейк лист с билети и  отворих URL-то. Предполагам, че става въпрос за това нещо:

```
<tbody>

<div  th:each="ticket : ${orderView.tickets}">
  <tr class="sums" th:if="${orderView.childQuantity > 0}">
    ...
  </tr>
  <tr class="sums" th:if="${orderView.studentQuantity > 0}">
    ...
  </tr>
  <tr class="sums" th:if="${orderView.regularQuantity > 0}">

  </tr>
  <tr class="sums" th:if="${orderView.overSixtyQuantity > 0}">

  </tr>
</div>

</tbody>
```

Данните в скоупа ще "изчезнат" когато всички променливи са равни на 0, както допускам е при теб. Иначе ще се появи нещо.

<img width="791" alt="Screenshot 2024-07-29 at 15 37 56" src="https://github.com/user-attachments/assets/8bbd74aa-609e-406a-b853-92c74c7cd8d3">

Освен това логиката ми изглежда грешна. Какво ще стане ако съм си купил 1 билет за възрастен и 1 за дете?

Поздрави,
Л.

**Comment by BlagoyVelinov** [comment]
Здравей, разбрах защо не се показва нищо. Проблема самата страница е
стилизиран с js и предполагам не се харесват много с thymeleaf. Ще направя
на ново таблицата без js и ще станат нещата. Но иначе и аз се чудя дали
логиката е вярна. Като го наглася да се визуализират данните ще пробвам с
други ако този вариант не става.
Хубав и успешен ден!

На пн, 29.07.2024 г., 15:41 ч. Lachezar Balev ***@***.***>
написа:
