### ISSUE TITLE
Невъзможност за стартиране на тестове.

### ISSUE THREAD

**Issue by dilyanValkov** [luchob/softuni-spring-may-2024#69]
Здравей, Лъчо! Започнах да пиша тестове на приложението, но при опит да запусна тест, получавам това:

![error](https://github.com/user-attachments/assets/abce4748-01a9-4977-b4d4-553929c06c78)

**Comment by luchob** [comment]
Здравей! 

Не беше излишна и връзка към проекта, но ще се опитаме да караме по картинка. С много голяма доза вероятност смятам, че не може да открие тестове, защото имената на пакетите ти не са според стандарта и започват и съдържат главни букви :-)

Поздрави,
Л.

**Comment by dilyanValkov** [comment]
Извинявам се. Заповядайте линк:  https://github.com/dilyanValkov/Fishing-farm-Zasmyano

**Comment by luchob** [comment]
Здравей, както казах - имената на пакетите трябва да започват и препоръчително да съдържат само малки букви. Ако ти се занимава, можеш дори да погледнеш кода на...  [грейдъл](https://github.com/gradle/gradle/blob/9b19add723ddfaae7722ee11134955e4517564a4/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java#L152-L153). :-)

Грешно: `Valkov.Fishing_Farm_Zasmyano.config`
Правилно: `com.valkov.fishingfarm.config`

Поздрави,
Л.
