### ISSUE TITLE
Gradle проблем

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#7]
![Capture](https://github.com/luchob/softuni-spring-may-2024/assets/118110958/ca246162-9b6a-4514-ae2e-ca18b9d52320)

Здравей, Лъчо,

всеки път когато създам проект с gradle ми излиза грешката от снимката.
С pom нямам този проблем.
Пробвах всякакви начина, за да го оправя, но не работят, дори от настройките опитвах.
Имаш ли идея какво да оправя.
Снимката специално е скрийншот от мобилето, което си свалих от твоето репо и при мен не работи.
Създавам си и нови проекти от spring intialzr, но пак като го отворя ми дава същата грешка. Версията на gragle ми е най-новата 8.8

**Comment by luchob** [comment]
Здравей!

Същото нещо случва ли се, ако направиш съвсем нов проект и го свалиш от [spring initializr](https://start.spring.io/) ?

Най-вероятната причина би могла да е някаква антивирусна програма или мрежови проблем. Всъщност gradle се опитва да си свали плъгънчето от тук: https://plugins.gradle.org/m2/org/springframework/boot/

Трябва да имаш достъп до това място и то да не е блокирано. Може ли да опиташ с нов проект, а също и достъпа до репозиторито?

Другото, което ме озадачава, че казваш че версията на грейдъл ти е 8.8, но това което виждам аз е че ползвам 8.7

https://github.com/luchob/softuni-spring-may-2024/blob/main/mobilele/gradle/wrapper/gradle-wrapper.properties

Поздрави,
Л.

**Comment by BogoevaPetya** [comment]
И при изцяло нов проект, който сама си създавам от spring initialzr грешката е същата. 
Иначе прикачвам как изглежда линка, който си ми дал, така ли изглежда и при теб?
![Uploading Capture2.PNG…]()

**Comment by luchob** [comment]
Добро утро!

Нещо не се е прикачило особено добре, но все пак това което се случва е доста странно. Отново бих погледнал потенциално блокиране от антивирусна или пък някакъв странен проблем със инсталацията на java и по-конкретно сертификатите, на които тя "вярва". На по простичък език - за да се достъпи нещо дето работи на https, java би трябвало да му "вярва". Предполагам, че ако изпълниш:
```
./gradlew build --debug -Djavax.net.debug=all
``` 
в директорията на проекта ще се види дали има подобна грешка, в output-a би трябвало да има нещо от рода на "PKIX path building failed".  За експеримент в gradle.properties може временно да добавиш:
```
systemProp.http.ssl.insecure=true
systemProp.http.ssl.allowall=true
systemProp.http.ssl.ignore.validity.dates=true
``` 

Също, пускането на `./gradlew build` с  опции `--debug` или `--info` биха могли да разкрият още детайли.

Ако все пак не се получи (проблемът се крие някъде в твоята инсталация на java или машината ти) ще ти пратя един maven файл за да можеш да си го пуснеш.

Поздрави,
Л.

**Comment by luchob** [comment]
Здравей, Петя! 

Тъй като няма отговор на горния ми пост ще затворя бъга, ако все пак проблема продължава или искаш да го борим някак пиши в същия бъг и ще го отворя наново.

Поздрави,
Л.
