### ISSUE TITLE
Error 405 при user login

### ISSUE THREAD

**Issue by RadostinStoyanov1** [luchob/softuni-spring-may-2024#70]
Здравей, пиша с молба за малко помощ по проекта ми, ако е възможно.

Link към проекта: https://github.com/RadostinStoyanov1/farmersMarketApp.git 

При опит да се логна с вече регистриран потребител, се появява следната грешка:
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jul 30 17:12:14 EEST 2024
There was an unexpected error (type=Method Not Allowed, status=405).
Method 'POST' is not supported.
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported

Би трябвало потребителя да се логне и да ме препрати към home страницата, но се появява горната грешка. Вече 4 часа ровя в SecurityConfig, LoginController, auth-login.html темплейта, но нищо не откривам. Търсих в нета също и дори и с ChatGPT пробвах, но и неговия съвет да добавя .loginProcessingUrl("/users/login") в SecurityConfig настройката, не помогна. Идеята му беше да подскажа на SpringSecurity, че от този url трябва да се вземе post заявката за login
 
 За бързо репродуциране на проблема - регистриране на потебител и след това опит за логване с неговите имейл и парола ще генерират грешката.
 
Съжалявам, че създавам това issue, защото обичам да се справям сам с проблемите, но вече нямам никаква идея какво друго мога да пробвам.

Поздрави и с пожелания за хубав и усмихнат ден,
Радостин

**Comment by luchob** [comment]
Здрасти!

1. Трябва да използваш интерфейсът `UserDetailsService` от спринг, а не твой си :-) Spring не разбира от твои интерфейси, така че изтрий `bg.softuni.farmers_market.service.UserDetailsService ` и вместо него използвай `org.springframework.security.core.userdetails.UserDetailsService` наготово.

2. Това не ти е необходимо -> `loginProcessingUrl("/users/login")`

3. Виж каква е разликата `failureForwardUrl VS failureUrl`. Обяснил съм я [тук](https://github.com/luchob/softuni-spring-may-2024/issues/6). Ти използваш `failureForwardUrl` но имаш `@GetMapping("users/login-error")` вместо PostMapping => грешка 405 неподдържан POST.

Поздрави и успех,
Л.

**Comment by RadostinStoyanov1** [comment]
Логването проработи вече :)
Сърдечно благодаря за помощта! Възхищавам се на добрите ти дела в помощ на всички нас - учещите се! Това, което правиш, е повече от страхотно!

С най-добри пожелания,
Радостин
