### ISSUE TITLE
Unit test problem

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#72]
Здрасти, Лъчо,

имам проблем с един unit test за регистрацията на юзър.
Използвам captor и като го рънна ми дава следната грешка:
Actually, there were zero interactions with this mock.

Wanted but not invoked:
mockUserRepository.save(
    <Capturing argument: UserEntity>

https://github.com/BogoevaPetya/DeliciousRecipes

Поздрави,
Петя

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей!

Все още съм тук, този автоматичен отговор го писахме на лекцията :-) Утре ще заминавам.

Wanted but not invoked:
mockUserRepository.save(

Означава, че очакваш че е извикано `mockUserRepository.save` но това не се е случило. Това е така, закщото тази проверка не минава:

```
        boolean passwordMatch = userRegisterDTO.getPassword().equals(userRegisterDTO.getConfirmPassword());
        if (!passwordMatch){
            return false;
        }
```

Защото няма confirm password. Опитай:

```
 public void testRegisterUser_Successful() {
        //Arrange
        UserRegisterDTO userRegisterDTO = new UserRegisterDTO();
        userRegisterDTO.setUsername("test");
        userRegisterDTO.setEmail("test@test.bg");
        userRegisterDTO.setPassword("secret");
        userRegisterDTO.setConfirmPassword("secret"); <---
``` 

Поздрави и успех на изпита!

П.П. Ако закъсаш, пускай въпрос пък каквото сабя покаже.
