### ISSUE TITLE
Как да добавя Rest Api-то (отделен проект) към основния в гитхъб

### ISSUE THREAD

**Issue by tony9701** [luchob/softuni-spring-may-2024#74]
*Връзка към проекта:* 

https://github.com/tony9701/propertiesApp

*Кратко описание:*

Възможно най-накратко опишете:

Здравей, Лъчо. Понеже работя и уча едновременно и нямам цялото време на света съм назад с лекциите и съм изпуснал.
Така днес започнах да си правя Rest Api-то като си направих нов проект с даденото ентити и тн. Въпроса ми е как да го пресъединя към основния ми проект в гитхъб без да омажа нещо другите файлове и директории понеже моя проект като го отваря няма отделни папки като твоя а направо си е самия проект със src папката ? Поздрави.

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by BlagoyVelinov** [comment]
Здравей, ако мога да помогна със съвет. Направи си ново репозитори и го направи коато отделен проект и добави към редми файла линк към Rest-api то!

**Comment by luchob** [comment]
Съгласен :-)

Поздрави и успех,
Л.
