### ISSUE TITLE
Въпрос относно логове

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#76]
Здравейте , искам да използвам някакъв туул за да имам на едно място логовете от приложението , но нямам идея кой би бил най-подходящ . В интернет прочетох , че щом използвам вече Grafana и Prometheus , би било най-добре да се насоча към Grafana Loki. Бихте ли ми дали съвет дали това е добра идея или има и по-добър и лесен туул ? Благодаря предварително и Ви пожелавам приятна почивка !

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здрасти, за съжаление не мога да те насоча към тривиален туул. 

Лично ние ползваме логинг системата на гугъл (бивш Stackdriver), заедно с един туул logtash който "обира" логовете и ги праща към гугъл. С помощта на logback ги обръщаме в JSON формат. Дали е лесно да го използваш от 0-та - не съм пробвал. Други колеги го ползваха заедно с elastic search. Ако искаш му хвърли едно очо, ще съм любопитен да ми пишеш ако имаш успех.

Поздрави,
Л.
