### ISSUE TITLE
Проблем с Update

### ISSUE THREAD

**Issue by DzhansuDikmemehmed** [luchob/softuni-spring-may-2024#78]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*

_Поставете [връзка](https://github.com/DzhansuDikmemehmed/MyProjectSoftuni) към проекта си по подобен начин._

*Кратко описание:*

Възможно най-накратко опишете:

1. Какво очаквате да се случи
Искам да напарвя ъпдейт с бутона в details.html, но нещо не мога да се справя. Мисля, че трябва да се направи с Put заявка, но някак си не мога да оправя нещата! Първо пробвах с get/post  даваше ми грешка 500, а сега ми дава 405.....
3. Какво всъщност се случва
4. (Желателно) Какво опитахте

*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които бързо може да се репродуцира проблемът.

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей, виждам че update бутона е линк, а не форма. Той би трябвало да отваря един коментиран по време на оправянето код ;-) Разкоментирах го и наистина има грешка 500. В такъв случай, трябва да се види самата грешка която е в `edit-appointment`, а не в `details`. Ето я от конзолата:

```
Exception evaluating SpringEL expression: "#dates.format(appointmentData.appointmentDateTime, 'yyyy-MM-dd\'T\'HH:mm')" (template: "edit-appointment" - line 35, col 94)
```

Тук има две неща. Първото е, че `dates` не работи с по-новото Java timing API, а второто е, че не му харесва много това `\`. Та, helper класа е temporals:

```
           <input type="datetime-local" id="appointmentDateTime" name="appointmentDateTime" th:value="${#temporals.format(appointmentData.appointmentDateTime, 'yyyy-MM-dd''T''HH:mm')}" class="form-control" required />
```

След това идав грешка но 2.

```
Property or field 'trainingType' cannot be found on object of type 'bg.softuni.myproject.service.dto.AddAppointmentDto' - maybe not public or not valid?
``` 
Действително няма `trainingType` защото си го кръстила `type`. Бърза проба "съживи" формата:

```
<option th:each="type : ${allTrainingTypes}" th:value="${type}" th:text="${type}" th:selected="${type == appointmentData.type}"></option>
```  

Тук е сменено `appointmentData.type` 

Поздрави,
Л.
