### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#8]
Привет,

имам едно питане относно error-ите, които се изписват при логин и регистрейшън формите.
Аз си задавам собствени месиджи от типа "Password length must be between 2 and 20 symbols", но след това освен тази грешка ми се появява още една "must not be blank". 
Пробвах да махна @NotBlank анотажията от полето, но тази грешка отново излиза.
Как мога да я огранича да не се показва, тъй като по условие на изпитните задачи не трябва да я има. а и няма логика веднъж да изписвам, че паролата не трябва да е празна и втори път, че трябва да е между 2 и 20 символа.
Прикачвам скрийншот на начина, по който ми излиза, а това е линк към репото на задачата: https://github.com/BogoevaPetya/DictionaryApp-Skeleton/tree/master/src/main/java/com/dictionaryapp
![Capture1](https://github.com/luchob/softuni-spring-may-2024/assets/118110958/5de62846-7a1c-413c-9959-d218ef980d1c)

**Comment by ShenolShengov** [comment]
Анотацията `@Size` ще хване empty stirng и може да смениш `@NotBlank` с `@NotNull`. На `@NotNull` може да й сложеш същото съобщение за length. Така гокато empty (или е по-малко/по-вече символа) ще се изписва грешката от `@Size`, а когато е null грешката от `@NotNull` и тъй като `@Size` приема null за валидна стойност няма как да се покажат и двете грешки.
![image](https://github.com/luchob/softuni-spring-may-2024/assets/113983927/3705528e-47c1-4e6e-be18-5d62b9f9a678)
