### ISSUE TITLE
Проблем при стартиране на контекст за Integration tests

### ISSUE THREAD

**Issue by IvayloM10** [luchob/softuni-spring-may-2024#80]
Здравей Лъчо,

Пиша да помоля за помощ със стартирането на тестовете и контекста там, ми излиза грешка load uri е null , която ми хвърля при опит за пускане на bankingApplicationTest, при единия случай е както в кода в проекта с @mockBean private ForexConfigurations ми седят кеу,url и base празни, при което ми се получава грешката, при премахване на  @mockBean private ForexConfigurations ми дава error cannot create bean "forexConfigurations". Моля за съдействие тъй като не знам от какво  се поражда грешката и как да я оправя, разбирам че въобще на чете yaml за forex: api: ... Ето линк към проекта в гитхъб: https://github.com/IvayloM10/banking_application. Същия проблем ще има и за loanApiConfig при него тъй като има log на конзолата се вижда че url е null, за него ще трябва да стартирате и https://github.com/IvayloM10/banking_application-loans.

С уважение,

Ивайло Милушев

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by IvayloM10** [comment]
![Screenshot 2024-08-05 003341 (1)](https://github.com/user-attachments/assets/13e191e3-1b4e-4dfb-ad7e-7f7f32154ddc)
![Screenshot 2024-08-05 003244](https://github.com/user-attachments/assets/d7f1693d-1764-41a8-9c3a-4fc4f6bec341)
Прикачвам два снипета с грешките за по-лесно разбиране

**Comment by luchob** [comment]
Привет, разбирам какъв е проблемът. Колегата имаше сходен, като можеш да провериш комуникацията [тук](https://github.com/luchob/softuni-spring-may-2024/issues/21#issuecomment-2210207697). Надявам се да помогне това решение.

Поздрави,
Л.
