### ISSUE TITLE
Integration tests issue

### ISSUE THREAD

**Issue by aChaushev** [luchob/softuni-spring-may-2024#81]
Привет Лъчо
линк към проекта: https://github.com/aChaushev/ArchitectsRepository

Всички Интеграционни тестове ми гърмят (юнит тестовете са ок), опитах да намеря решение включително с ChatGPT, но не успях. Моля за съдействие. 

Поздрави 
А. Чаушев

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей!

Първото нещо, което виждам и заради което тестовете няма да сработят е употребата на `columnDefinition` която се вижда и в ексепшъна на теста. Колегата имаше подобен проблем, виж обяснението [тук](https://github.com/luchob/softuni-spring-may-2024/issues/36#issuecomment-2227206200). Може би не е единствения проблем, но със сигурност е проблем :-)

Поздрави,
Л.

**Comment by aChaushev** [comment]
ОК мерси, друг проблем, с който ми гърмят е свързан с data.sql и AppConfig->dataSourceInitializer при инициализацията на данните ->

- org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceInitializer' defined in class path resource [aChaushev/architects/config/AppConfig.class]: Failed to execute SQL script statement #11 of class path resource [data.sql]: INSERT.....
- Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #11 of class path resource [data.sql]: INSERT ....
- Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint ; SYS_CT_10133 table: PROJECTS column: IS_FAVORITE
- ......

Има ли начин да избегна използването им от Интеграционните тестове или друг начин, така че да запазя инизиализацията на данните от data.sql при първо стартиране на web проекта?

Поздрави

**Comment by luchob** [comment]
Здравей!

В този случай проблема е, че INSERT заявката в data.sql, която прави insert в таблицата projects и липсва стойност за  favorite колонката, която не може да е null. Добави я в списъка с колонките `INTO projects (...) values (..)` наедно с нейната стойност.

Може би не е единствения проблем, но със сигурност е проблем :-)

Поздрави,
Л.
