### ISSUE TITLE
Проблем при деплойването на проекта

### ISSUE THREAD

**Issue by ATsonev** [luchob/softuni-spring-may-2024#83]
Здравей, Лъчо
Имам проблем при деплойването на проекта. Гледах лекцията за деполойване в Microsoft Azure и следвах стъпките ти, но в момента, в който се качи приложението и аз се опитах да влезна и излиза тази грешката (This page isn’t working [easyserves-easyserves.azuremicroservices.io](http://easyserves-easyserves.azuremicroservices.io/) redirected you too many times ERR_TOO_MANY_REDIRECTS). Навсякъде търсих как да я оправя - изтривах бисквити и кеша, презареждах приложението и дори направих всичко нанаво, но нищо не помогна. Опитах да променя в security-то да има и username и password, както и махнах CustomSuccessHandler-a, но и това не помогна. Като си го пусна на локалния хост нямам никакви проблеми и всичко варви както трябва. Дали има шанс да се дължи на това, че промених в pom.xml-a от java 11 на 17 и от war на jar. Може ли да ми помогнеш или поне да ми дадеш някакъв съвет. 

https://github.com/ATsonev/RestaurantSoftware

![image](https://github.com/user-attachments/assets/c6618e72-e23d-4140-b3af-1c8490391c86)

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей! Трудно мога да ти помогна, но това което бих направил е:

1. Когато зареждаш отвори devtool-s на браузъра и проследи какви заявки минават което би могло да е сериозен жокер.
2. Разгледай и логовете на сървъра в azure.

Съмнявам се, че триенето на кешове и кукита ще помогне на проекта да тръгне :-)

Поздрави,
Л.
