### ISSUE TITLE
Проблем с Update

### ISSUE THREAD

**Issue by DzhansuDikmemehmed** [luchob/softuni-spring-may-2024#84]
_Попълнете отделните секции отдолу и изтрийте упътванията._

*Връзка към проекта:*

_Поставете [връзка](https://github.com/DzhansuDikmemehmed/MyProjectSoftuni/tree/main) към проекта си по подобен начин._

*Кратко описание:*

Възможно най-накратко опишете:
Здарвейте! Проблемът с този бутон(в details.html) продължава при мен. когато натисна update дава 302 и връща в първоначалното сътояние на страницата. правя го с put, но нещо не се случват нещата. 

*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които бързо може да се репродуцира проблемът.

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by DzhansuDikmemehmed** [comment]
И също така искаж да питам за логоута, ако съмна връзка като тази:http://localhost:8080/appointments/1 и цъкна логоут ми дава грешка :( не можах да рабера причината за това

**Comment by luchob** [comment]
Добро утро!

Проблемите едва ли опират в това дали заявката е POST/PUT, по-скоро куца нещо фундаментално. Имаш следната форма

```
<form th:method="post" th:action="@{/appointments/update/{id}(id=*{appointmentDetails.id})}">
                 <input type="hidden" name="_method" value="put" />

                   <button class="btn btn-update btn-action" type="submit">
                    <i class="fas fa-edit"></i> Update
                </button>
               </form>
```

Когато я събмитнеш по-мрежата започва да пътува една празна форма. Вътре няма нищо, освен csrf тоукън и този ненужен _method. Стига до контролера ти:
```
    @PutMapping("/appointments/update/{id}")
    public String updateAppointmentPut(
             ....
            @Valid  AddAppointmentDto appointmentData <---- !
           ...
         ) {

```

Естествено AddAppointmentDto е празно и невалидно.  В bindingResult-a е пълно с грешки и ето го 302:

```
if (bindingResult.hasErrors()) {
            return "redirect:/appointments/update/" + id;
        }
```
 
Трябва да си отговориш на въпроса как точно искаш да закараш данните до сървъра, какво да мине по-мрежата, къде трябва да е формата и всичките и контроли вътре и т.н.

Относно logout бутона:

``` 
<form method="post" th:action="@{users/logout}" class="logout-form">
                                <button type="submit" class="btn btn-logout" th:text="#{nav_bar_logout}">Logout</button>
                            </form>
``` 

Това нещо -> `@{users/logout}` се нарича релативно URL. Релативните URL-та се наричат така, защото са относителни на пътя от който ги извикваш. Например ако в браузъра си тук:
```
http://localhost:8080/appointments/update/1
```
При логаут ще се извика: `http://localhost:8080/appointments/update/users/logout` което разбира се няма да работи.

Това нещо пък -> `@{/users/logout}` се нарича абсолютно URL защото е абсолютно спрямо адреса на сървъра. Например ако в браузъра си тук:
```
http://localhost:8080/appointments/update/1
```
При логаут ще се извика: `http://localhost:8080/users/logout` което би трябвало да работи.

Поздрави,
Л.
