### ISSUE TITLE
Проблем с data.sql файл при стартиране на тестовете

### ISSUE THREAD

**Issue by BogoevaPetya** [luchob/softuni-spring-may-2024#85]
Здрасти, Лъчо,

имам проблем с data.sql файла, когато стартирам тестовете. Без него всички минават на 100%, добавя ли обаче 1/3 oт тестовете не минават.
Изписва ми 
Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]
Както и че тези таблици, в които се опитвам да налея информация не съществуват.
Може ли помощ?

https://github.com/BogoevaPetya/DeliciousRecipes

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей, Петя!

Както споменах [тук](https://github.com/luchob/softuni-spring-may-2024/issues/75#issuecomment-2265582959),  HSQLDB и MySQL са различни бази и поддържат малко по-различен SQL синтаксис. HSQLDB например (към който се изпълнява `data.sql` скрипта при интегрейшън тестовете), няма да поддържа символи като ` които [виждам в твоя скрипт](https://github.com/BogoevaPetya/DeliciousRecipes/blob/master/src/main/resources/data.sql#L1).

Поздрави,
Л!
