### ISSUE TITLE
UnitTest на Entity наследяващо ID от BaseEntity

### ISSUE THREAD

**Issue by mario9502** [luchob/softuni-spring-may-2024#86]
Здравей Лъчо, как мога да тествам логиката на findById метод когато самото Entity няма ID поле в него а го наследява от BaseEntity? Когато пробвам първо "verify(mockedEntityRepository).save(entityCaptor.capture());" и след това с getValue да инстанцирам обект и да взема id-to с entity,getId, то тогава id e null.

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей!

Липсва пример и повечко контекст към въпроса. Затова отговарям малко наслука :-) Допускам, че създаваш нов обект, напр:

```
Entity newEntity = new Entity();
newEntity.setProperty("Pesho");
repo.save(newEntity);
```

Вероятно newEntity просто няма ID когато го записваш. Ако не е така, ще ми е необходима връзка към проблемния тест в проекта.

Поздрави,
Л.

**Comment by mario9502** [comment]
https://github.com/mario9502/RegalCinema/tree/master ето лик към репо-то в
случая се опитвам да направя тест на CinemaServiceImpl и в частност на
findById, но нещо не се досещам от къде мога да взема това id в тестовете.

**Comment by luchob** [comment]
Нещо такова?

```
 @Test
    void testFindById_Successfull() {
        long testId = 3;
        Cinema testEntity = createTestEntity();
        
        when(mockedCinemaRepository.findById(testId))
            .thenReturn(Optional.of(testEntity));
        
        CinemaInfoDto foundCinemaInfoDTO = toTest.findById(testId);
        
        // Assertions...
        Assertions.assertEquals(testEntity.getDescription(), foundCinemaInfoDTO.getDescription());
        ...
    }
```

Поздрави 🌴,
Л.

**Comment by mario9502** [comment]
Благодаря. Приятна почивка!
