### ISSUE TITLE
Проблем при стартиране на интеграционни тестове

### ISSUE THREAD

**Issue by IliyanGeorgiev02** [luchob/softuni-spring-may-2024#87]
Здравейте, написал съм няколко интеграционни теста, но при стартиране получавам  тази грешка. 
![integrationTestError](https://github.com/user-attachments/assets/b43a778e-9422-4296-82f5-fce42c7b4190)
Пробвах да сменя версията на jUnit, проверих имената на пакетите и тяхното местоположение в проекта, анотациите, които съм използвал. Добавил съм hsqldb в проекта и съм създал нов application.properties файл в test папката с необходимата информация в него. Това е проекта https://github.com/IliyanGeorgiev02/JavaWebFinalProject . Ще бъда много благодарен за Вашия съвет и съдействие.

**Comment by luchob** [comment]
<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!<p>:rocket: Успешно и приятно програмиране! :rocket:</p>

**Comment by luchob** [comment]
Здравей!

Със сигурност има проблем, когато пакетите ти започват с главна буква, както е при теб.

Ако искаш погледни за повече подробности [тук](https://github.com/luchob/softuni-spring-may-2024/issues/69).

Поздрави,
Л.
