### ISSUE TITLE
Проблем с ъплоуд на картинка

### ISSUE THREAD

**Issue by IvanRusenov** [luchob/softuni-spring-may-2024#9]
*Връзка към проекта:*
https://github.com/IvanRusenov/Online-Shop

*Кратко описание:*

1. Опитвам се да ъплоудна картинка

2. Файлът се ъплоудва там, където искам, данните се запазват в базата, но картинката не се показва. Показва се след рестарт на приложението (не винаги, понякога се показва веднага).

*Стъпки за репродуциране:*

- регистрация 
- логин
- add 

и виждаме поблема, информацията е там, но картинката я няма. След рестарт на приложението картинката се рендерира успешно.

**Comment by luchob** [comment]
Здрасти, Ванка!

Обяснимо е, че няма да стане по този начин, дори ако отвориш src на въпросната картинка ще получиш първи впечатления.

<img width="712" alt="Screenshot 2024-06-26 at 14 48 13" src="https://github.com/luchob/softuni-spring-may-2024/assets/10339738/3b30e084-0f81-4ba9-8261-920b7e535cb2">

Това на една страна, обаче. От друга страна пътя, по който си тръгнал ще ти доведе доста големи главоболия:

- това, което се опитваш да направиш очевидно е зависимо от OS-а ти (напр, сепаратор)
- дори да го докараш, няма да работи във всички ситуации. Например, преди да се деплойне едно спринг приложение често се пакетира като един "ueber jar" който не се "expload"-ва и там няма как да пишеш в клас пътя ти. С други думи като деплойнеш в "клауда" няма да има оправия.
- ще те мъчат наглед странни проблеми като "След рестарт на приложението картинката се рендерира успешно". Последното е защото всъщност приложението ти се стартира не от src папката, а от target където maven го мести при компилация :-) 

Затова мога да ти предложа няколко варианта:

1) Най-близкият до подхода ти, опитай да настроиш спринг така че да имаш допълнителна локация за статичните ресурси на някакъв абсолютен път. В.ж. как става в т.2.2 [тук](https://www.baeldung.com/spring-mvc-static-resources#2-custom-directories).

2) Пази картинката в ДБ. Бяхме правили пример миналата година. В.ж. [тук](https://github.com/luchob/softuni-feb2023/tree/a72b6d87eae2d874c9fc7cdd5a2ed08a7345a78f/dbimages).

3) Комбинация от 1 и 2 - т.е. записваш ги на определен абсолютен път и вземаш даунлоад контролера от опция 2

4) Ползваш външен сторидж като cloudinary

Надявам се да помогнах.

Поздрави,
Л.
2) При желание, пази файла в ДБ вместо в

**Comment by IvanRusenov** [comment]
Много благодаря за бързата реакция и съдействието.
